### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mastrobardo** [tststs/atom-ternjs#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/davidetemp/.atom/packages/atom-ternjs/lib/atom-ternjs-autocomplete.coffee:35

TypeError: Cannot read property 'length' of undefined
  at AtomTernjsAutocomplete.module.exports.AtomTernjsAutocomplete.getEditorView (/Users/davidetemp/.atom/packages/atom-ternjs/lib/atom-ternjs-autocomplete.coffee:35:9)
  at AtomTernjsAutocomplete.module.exports.AtomTernjsAutocomplete.cancelAutocompletion (/Users/davidetemp/.atom/packages/atom-ternjs/lib/atom-ternjs-autocomplete.coffee:33:10)
  at AtomTernInitializer.callPreBuildSuggestions (/Users/davidetemp/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:107:16)
  at /Users/davidetemp/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:91:8
  at Emitter.module.exports.Emitter.emit (/Users/davidetemp/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/davidetemp/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:25

```

### Commands

```
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "ternjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.2.3
autocomplete-plus, v1.0.0
color-picker, v1.2.6
emmet, v2.3.0
linter, v0.9.0
minimap, v3.4.9
travis-ci-status, v0.11.1
vim-mode, v0.22.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by alem0lars** [comment]
I got this error today while editing Ruby file..
How is it possible?
