### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by Eschon** [tststs/atom-ternjs#101]
Clicked on a file path in Deprecation cop. 
When the file opened I got this error.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.8

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn ENOTDIR
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at Object.exports.spawn (child_process.js:977:9)
    at BufferedNodeProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at BufferedNodeProcess.BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at new BufferedNodeProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-node-process.js:27:49)
    at Server.module.exports.Server.start (/Users/egon/.atom/packages/atom-ternjs/lib/atom-ternjs-server.coffee:42:31)
    at Manager.module.exports.Manager.startServer (/Users/egon/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:148:38)
    at Manager.module.exports.Manager.checkPaths (/Users/egon/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:199:28)
    at /Users/egon/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:60:17
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-ternjs": {
    "useSnippets": false,
    "doNotAddParantheses": true,
    "documentation": false,
    "urls": false,
    "origins": false,
    "inlineFnCompletion": false
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.0.0
atom-ternjs, v0.6.8
linter, v1.2.3
linter-csslint, v0.0.14
linter-jscs, v1.12.0
linter-jshint, v0.1.7
linter-rubocop, v0.2.7
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by Eschon** [comment]
I can still reproduce this with atom-ternjs 0.7.1 on Atom 1.0.4
If you have troubles reproducing it try this:

1) Install `linter` and `linter-rubocop`
2) Open the Deprecation cop
3) Expand the deprecation warning for `linter-rubocop` and click on any link that links to a .js file.

**Comment by donCarlosOne** [comment]
Getting this too and it might be related to a path that seems to be hardcoded  somewhere.  I'm receiving the following error just prior to the one described here:

Failed to spawn command
/Applications/Atom.app/Contents/resources/app/apm/bin/apm. Make sure /Applications/Atom.app/Contents/resources/app/apm/bin/apm is installed and on your PATH

I say hardcoded because apm IS in my path already but is located at
apm -> /Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm

which is how Atom has installed itself.

**Comment by jordanbtucker** [comment]
#144 may have fixed this.

**Comment by Eschon** [comment]
Is this already in a published release?
I can't test this right now since there are no deprecation warnings.

**Comment by jordanbtucker** [comment]
Yes, this is in 0.8.3.

**Comment by Eschon** [comment]
Ok I'll check it as soon as I find something with a deprecation warning.
