### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by xxsnakerxx** [tststs/atom-ternjs#102]
**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.8

### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:689

TypeError: Cannot read property 'getTokenIterator' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:689:42)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1135:35)
  at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2305:33)
  at /Users/xxsnakerxx/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:63:24
  at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:842:9)
  at TextBuffer.module.exports.TextBuffer.backwardsScanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:853:19)
  at Type.module.exports.Type.queryType (/Users/xxsnakerxx/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:61:12)
  at /Users/xxsnakerxx/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:166:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1591:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:400:20)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:345:12)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:175:32)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:136:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:722:7)
  at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:134:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1337:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1582:9)
  at TextEditor.module.exports.TextEditor.setCursorBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1336:19)
  at GoToLineView.module.exports.GoToLineView.confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/go-to-line/lib/go-to-line-view.js:119:14)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/go-to-line/lib/go-to-line-view.js:55:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -4:19 editor:newline (atom-text-editor.editor.is-focused)
     -4:18.7.0 core:paste (atom-text-editor.editor.is-focused)
     -4:18.1.0 core:save (atom-text-editor.editor.is-focused)
 12x -3:27.9.0 core:undo (atom-text-editor.editor.is-focused)
  2x -3:15.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:53.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -2:52.7.0 core:save (atom-text-editor.editor.is-focused)
  4x -2:04.1.0 core:undo (atom-text-editor.editor.is-focused)
  2x -1:56.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:41.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:41 core:save (atom-text-editor.editor.is-focused)
     -1:04.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:57.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:55.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.4.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dash"
    ]
  },
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-ternjs, v0.6.8
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.5.8
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.2.3
linter-jshint, v1.0.4
minimap, v4.11.2
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
pigments, v0.8.4
pretty-json, v0.4.1
react, v0.12.4

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
@tststs you can safely close this issue. It was an atom issue that was presumably fixed a long time ago. Nobody was able to repro it lately.

**Comment by tststs** [comment]
ok cool, thank you!
