### ISSUE TITLE
Failed to load the atom-ternjs package

### ISSUE THREAD

**Issue by z1ng** [tststs/atom-ternjs#112]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Unknown Windows Version
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.7.1

### Stack Trace

Failed to load the atom-ternjs package

```
At Cannot find module 'loophole'

Error: Cannot find module 'loophole'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\tx\AppData\Local\atom\app-1.0.7\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\tx\.atom\packages\atom-ternjs\lib\atom-ternjs-provider.coffee:4:14)
    at Object.<anonymous> (C:\Users\tx\.atom\packages\atom-ternjs\lib\atom-ternjs-provider.coffee:130:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\tx\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "terminal-panel"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.2
atom-material-ui, v0.5.14
atom-ternjs, v0.7.1
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.3
minimap, v4.12.3
run-in-browser, v0.1.3

# Dev
No dev packages
```

**Comment by tststs** [comment]
Please try to re-install the package.
loophole is an dependency and should be installed correctly to node_modules.
