### ISSUE TITLE
Error everytime I start atom

### ISSUE THREAD

**Issue by olivierchatry** [tststs/atom-ternjs#122]
Hello ! 
First thanks for the addon, but I have a problem : everytime I start atom I get this error message : 

events.js:141 throw er; // Unhandled 'error' event ^ Error: listen EMFILE 127.0.0.1 at Object.exports._errnoException (util.js:734:11) at exports._exceptionWithHostPort (util.js:757:20) at Server._listen2 (net.js:1158:19) at listen (net.js:1203:10) at net.js:1303:9 at dns.js:66:18 at process._tickCallback (node.js:357:13) at Function.Module.runMain (module.js:495:11) at startup (node.js:120:16) at node.js:877:3

I'm not sure what to do to make it disappears :(

**Comment by tststs** [comment]
Does disabling ```atom-ternjs``` removes the error from atom?
Haven't found anything with the provided information and no clue what is going on.

**Comment by olivierchatry** [comment]
It was the limit on number of open files. It seems tern is a bit of a file
hugger :)

**Comment by Sam2304** [comment]
I seem to be having a similar issue:
```atom-ternjs
events.js:141 throw er; // Unhandled 'error' event ^ Error: listen EMFILE 127.0.0.1 at Object.exports._errnoException (util.js:814:11) at exports._exceptionWithHostPort (util.js:837:20) at Server._listen2 (net.js:1201:19) at listen (net.js:1250:10) at net.js:1353:9 at doNTCallback3 (node.js:449:9) at process._tickCallback (node.js:355:17) at Function.Module.runMain (module.js:471:11) at startup (node.js:125:18) at node.js:960:3
```

Not sure why this is hapenning, I've been trying to get atom-tern up and running, but have had problem after problem.. Nearly there now I think!

System: Ubuntu 15.04 (Vivid) x64
Atom: 1.0.19

I can confirm that the problem only arises when atom-tern is enabled, disabling it prevents this error from occurring.  At one point I appear to have had tern running, but I got a bunch of POST errors in the console whenever I selected text.  Whilst tern was running, it was not responding as it should have, perhaps that is related?

**Comment by jordanbtucker** [comment]
This seems to be a duplicate of #75. Can you try the suggestions there and see if it helps?
