### ISSUE TITLE
TypeError: undefined is not a function when dealing with `then` or `catch` method of `q` module

### ISSUE THREAD

**Issue by rbecheras** [tststs/atom-ternjs#133]
Atom ternjs always throws me an exception `TypeError: undefined is not a function` when dealing with `then` or `catch` method of `q` module: 

    atom-ternjs
    TypeError: undefined is not a function 
      at /home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:633:37 
      at fn.computeRet (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) 
      at fn.computeRet (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) 
      at fn.computeRet (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/def.js:257:26) 
      at computeReturnType (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1826:19) 
      at typeFinder.CallExpression (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1883:14) 
      at findType (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21) 
      at typeFinder.MemberExpression (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1886:41) 
      at findType (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1917:21) 
      at computeReturnType (/home/remi/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1817:14)

For example, when coding this block:

```js
exports.fetchRelations = function(req,res,next){
  if (!req.distribetage || !req.distribetage.dataValues || !req.distribetage.dataValues.iddistribetage) {
    return next('Pas de distributeur auquel associer ses models liés');
  }
  Typdistri.findById({req.distribetage.dataValues.idTypdistri}).then(function(typdistri){
    req.distribetage.dataValues.typdistri = typdistri;
    return Modeldistri.findById({req.distribetage.dataValues.idModeldistri});
  }).then(function(modeldistri){
    req.distribetage.dataValues.modelditri = modeldistri;
    return Puidistri.findById(req.distribetage.dataValues.idPuidistri);
  }).then(function(puidistri){
    req.distribetage.dataValues.puidistri = puidistri;
    return next();
  }).catch(function(err){
    console.error(err);
    return next('Impossible d\'associer certains models liés');
  });
};
```

... it happens each time I tape `.then(function(` or `.catch(function(`. In fact, at the first dot, and for each new char following.

**Comment by tststs** [comment]
Could you please provide information about config and used plugins?
