### ISSUE TITLE
TypeError: Cannot read property 'type' of null at Array.isImport 

### ISSUE THREAD

**Issue by thachduongria** [tststs/atom-ternjs#135]
i dont know why.

[details below]

atom-ternjs
TypeError: Cannot read property 'type' of null at Array.isImport (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/plugin/commonjs.js:57:13) at Object.signal.mixin.findIn (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/plugin/modules.js:73:28) at Object.signal.mixin.isImport (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/plugin/modules.js:79:44) at Object.findCompletions (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/plugin/modules.js:261:18) at Object.signalReturnFirst (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/lib/signal.js:34:27) at Object.findCompletions [as run] (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:668:26) at run (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:254:30) at Object.exports.withContext (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:862:18) at /Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:262:13 at analyzeAll (/Users/duongthach/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:376:15)

**Comment by agileago** [comment]
+1

when i type `var a` . it will display

**Comment by tststs** [comment]
Please report this issue directly to marijnh/tern

**Comment by tststs** [comment]
Does the issue still exists?
