### ISSUE TITLE
Uncaught TypeError: Cannot read property 'provide' of undefined

### ISSUE THREAD

**Issue by nisargjhaveri** [tststs/atom-ternjs#14]
### To reproduce
1. Install atom-ternjs from atom settings

**Note:** I am behind a proxy and firewall, if that helps.

-------
**Atom Version**: 0.172.0
**System**: linux 3.14.1-031401-generic
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'provide' of undefined

```
At /home/.../.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:73

TypeError: Cannot read property 'provide' of undefined
  at AtomTernInitializer.activatePackage (/home/.../.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:73:45)
  at AtomTernInitializer.init (/home/.../.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:76:6)
  at /home/.../.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:104:10
  at stdout (/home/.../.atom/packages/atom-ternjs/lib/atom-ternjs-server.coffee:16:7)
  at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```

### Commands

```
     -30:39.4 command-palette:toggle (atom-text-editor.editor)
     -30:35.8 core:move-down (atom-text-editor.editor.mini)
     -30:35.5 core:confirm (atom-text-editor.editor.mini)
     -30:35.5 settings-view:uninstall-packages (atom-text-editor.editor)
     -30:13.9 core:select-up (atom-text-editor.editor)
  2x -30:13.5 core:backspace (atom-text-editor.editor)
     -30:06.9 application:new-window (atom-text-editor.editor)
     -30:00.0 pane:show-next-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "metrics"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.4.9
autocomplete-plus, v2.1.0
color-picker, v1.4.4
docblockr, v0.5.8
highlight-selected, v0.7.0
project-manager, v1.15.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by tststs** [comment]
Pls update atom to >= 0.177.
Duplicate of <a href="https://github.com/tststs/atom-ternjs/issues/11">#11</a>

**Comment by nisargjhaveri** [comment]
Works. Thanks.
