### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by zmLGBBM** [tststs/atom-ternjs#147]
1. ...Open atom
2. ...Open settings panel
3. ...Re-open atom

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.8.3

### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:854

TypeError: path must be a string
    at TypeError (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at Helper.module.exports.Helper.isDirectory (C:\Users\Clive\.atom\packages\atom-ternjs\lib\atom-ternjs-helper.coffee:25:8)
    at Manager.module.exports.Manager.checkPaths (C:\Users\Clive\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:122:36)
    at C:\Users\Clive\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:38:8
    at Emitter.module.exports.Emitter.emit (C:\Users\Clive\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at Project.module.exports.Project.addPath (C:\Users\Clive\AppData\Local\atom\app-1.0.19\resources\app.asar\src\project.js:279:29)
    at EventEmitter.<anonymous> (C:\Users\Clive\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:41:32)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-alignment, v0.12.1
atom-ternjs, v0.8.3
atom-typescript, v7.4.1
atom-yeoman, v0.3.15
autocomplete-bibtex, v0.6.1
autocomplete-paths, v1.0.2
autocomplete-python, v0.6.2
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.10
json-schema, v0.1.15
linter, v1.8.1
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
omnisharp-atom, v0.25.0
pigments, v0.17.1
python-tools, v0.6.5
terminal-plus, v0.9.0
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by zmLGBBM** [comment]
It somehow no longer throwing errors.

**Comment by jordanbtucker** [comment]
This is surely related to the fix in #144. I'm not able to reproduce this issue, but I've got a couple ways to fix it. If you can figure out how to consistently reproduce it, please let me know.

**Comment by zmLGBBM** [comment]
@jordanbtucker Well, for me, it's to open settings panel and close atom, then re-open atom, the error will appear in the top right corner then.

**Comment by jordanbtucker** [comment]
Since I can't reproduce this, do you mind checking if this fixes the issue?

Close all instances of Atom.

Run:
```sh
apm uninstall atom-ternjs
git clone https://github.com/jordanbtucker/atom-ternjs -b fs-catch
cd atom-ternjs
npm install
apm ln .
```

Test again.

After testing you can run:

```sh
apm unlink atom-ternjs
apm install atom-ternjs
```

**Comment by zmLGBBM** [comment]
@jordanbtucker Great! Works like a charm!
