### ISSUE TITLE
Installing “atom-ternjs@0.8.4” failed.

### ISSUE THREAD

**Issue by kminehart** [tststs/atom-ternjs#152]
>npm WARN addRemoteGit Error: Command failed: 
>npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
>npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
>npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
>npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
>npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
>npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
>npm WARN addRemoteGit  marijnh/tern resetting remote C:\Users\\\<name\>\\.atom\.apm\_git-remotes\git-github-com-marijnh-tern-git-36bbc24d because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }

... (clone errors ...

>npm ERR! git fetch -a origin (https://github.com/marijnh/tern.git) fatal: Unable to find remote helper for 'https'
If it helps, I'm at work and port 22 is closed.  As is most everything except 80 and 443, so when it fails over and tries to use git over ssh it fails with "connection refused".  100% on my end?  https isn't blocked so I can't imagine why it would fail the first time.  Git is installed on my path, and I have even reinstalled it.

**Comment by tststs** [comment]
you may try:

```$ apm config set registry http://registry.npmjs.org/ ```

but this is a security risk.

**Comment by k5e** [comment]
@tststs, the issue is not https vs. http. It is that the install procedure tries to clone a repository with ssh: 
```
npm WARN addRemoteGit  git://github.com/ternjs/tern.git#d91740fa...
```
@kminehart and I, we are sitting behind a proxy that allows only ports 80 (http) and 443 (https) to connect outside resources. Every other port is denied.
