### ISSUE TITLE
Error at startup listen EMFILE 127.0.0.1 

### ISSUE THREAD

**Issue by metal3d** [tststs/atom-ternjs#157]
Hi,

Installed laste version 0.8.4 (if I'm not wrong)

I've got:
```
atom-ternjs
events.js:141 throw er; // Unhandled 'error' event ^ Error: listen EMFILE 127.0.0.1 at Object.exports._errnoException (util.js:814:11) at exports._exceptionWithHostPort (util.js:837:20) at Server._listen2 (net.js:1201:19) at listen (net.js:1250:10) at net.js:1353:9 at doNTCallback3 (node.js:449:9) at process._tickCallback (node.js:355:17) at Function.Module.runMain (module.js:471:11) at startup (node.js:125:18) at node.js:960:3
Close All
```

and

```
tern exited with code: 1.
Restart the server via Packages -> Atom Ternjs -> Restart server
```
The .tern-project is:

```
{
  "ecmaVersion": 6,
  "libs": [],
  "loadEagerly": [
    "/home/pferlet/src/DCP-AngularModules/**/*.js"
  ]
}
```

I really don't know why and how - but I never get atom-ternjs working on my computer :(

**Comment by jordanbtucker** [comment]
This seems to be a duplicate of #75. Can you try the suggestions there and see if it helps?
