### ISSUE TITLE
`export from` throws errors

### ISSUE THREAD

**Issue by amannn** [tststs/atom-ternjs#167]
Steps to reproduce below:

1. Write a JavaScript file with the following line: `export * as ShopActions from './ShopActions';`
2. Edit it

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of null

```
At /Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68

TypeError: Cannot read property 'type' of null
    at c (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:29)
    at Object.skipThrough (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.ExportAllDeclaration (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:343:3)
    at c (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.Program.base.BlockStatement [as Program] (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:180:5)
    at c (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.recursive (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:69:5)
    at Object.exports.analyze (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1713:10)
    at /Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:272:13
    at Object.exports.withContext (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:865:18)
    at analyzeFile (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:269:11)
    at analyzeAll (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:374:11)
    at doRequest (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:237:7)
    at Object.signal.mixin.request (/Users/Jan/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:161:7)
    at Server.respond (/Users/Jan/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:417:17)
    at IncomingMessage.<anonymous> (/Users/Jan/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:95:16)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
     -0:36.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:36 editor:duplicate-lines (atom-text-editor.editor.is-focused)
  3x -0:35.4.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:34.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:34 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:29.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:27.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:03.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:03.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:03.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "Tern",
      "Zen",
      "Zen"
    ]
  },
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-jasmine, v0.8.1
atom-jshint, v2.0.0
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
atom-ternjs, v0.9.1
color-picker, v2.0.13
docblockr, v0.7.3
editorconfig, v1.2.2
emmet, v2.3.15
jsformat, v0.9.0
last-cursor-position, v0.9.0
linter, v1.11.2
linter-eslint, v5.2.4
minimap, v4.16.2
pigments, v0.19.1
react, v0.12.10
set-syntax, v0.3.0
split-diff, v0.4.5

# Dev
No dev packages
```

**Comment by tststs** [comment]
Is `export * as ShopActions from './ShopActions';`valid ES6?

I thought only:

`export * from './ShopActions';`

is supported for the export syntax. Correct me if i'm wrong.

**Comment by amannn** [comment]
Hm, I'm not sure actually. Babel [transforms it correctly](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=export%20*%20as%20ShopActions%20from%20'.%2FShopActions'%3B).

It just made sense to me, so I tried it :).

**Comment by tststs** [comment]
Have a look here: http://www.2ality.com/2015/07/es6-module-exports.html.
Searched the web also, haven't found anything that describes the above syntax as valid.

Anyway, an error shouldn't be thrown. So you may report the issue to https://github.com/ternjs/tern, cause it's thrown from `acorn`

Greetings.

**Comment by amannn** [comment]
I guess your right. Then I'll fix it in my code – never mind.
