### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by thatsprettyfaroutman** [tststs/atom-ternjs#172]
[Enter steps to reproduce below:]

1. Opened a js-file 

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.10.2

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /Users/viljami/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:352

TypeError: Cannot read property 'querySelector' of null
    at /Users/viljami/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:352:45
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:282:9)
    at Manager.registerEvents (/Users/viljami/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:325:42)
    at Manager.activate (/Users/viljami/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:59:10)
    at Manager.startServer (/Users/viljami/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:163:14)
    at Manager.initServers (/Users/viljami/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:127:14)
    at Manager.init (/Users/viljami/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:44:10)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "git-plus",
      "auto-indent",
      "SFTP-deployment",
      "jsdoc",
      "language-cshtml",
      "merge-conflicts",
      "project-manager",
      "Remote-FTP",
      "atom-color-highlight"
    ],
    "packagesWithKeymapsDisabled": [
      "tidy-tabs"
    ]
  },
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.3
atom-pair, v2.0.10
atom-spotify2, v2.1.2
atom-ternjs, v0.10.2
change-case, v0.6.0
chester-atom-syntax, v0.1.1
emmet, v2.3.15
file-icons, v1.6.12
minimap, v4.16.2
php-cs-fixer, v2.5.1
php-twig, v4.0.0
remote-sync, v3.5.0
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by tststs** [comment]
Is `Use Shadow DOM` disabled?

**Comment by thatsprettyfaroutman** [comment]
Thanks for the fix! :)
