### ISSUE TITLE
Uncaught Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by nicholashu** [tststs/atom-ternjs#178]
[Enter steps to reproduce below:]

1. open Atom

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.10.3

### Stack Trace

Uncaught Error: Cannot find module 'glob'

```
At module.js:338

Error: Cannot find module 'glob'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nick/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:8:12)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Manager.startServer (/Users/nick/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:136:16)
    at Manager.initServers (/Users/nick/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:127:14)
    at Manager.init (/Users/nick/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:44:10)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.10.3
express-complete, v0.2.0

# Dev
No dev packages
```

**Comment by tststs** [comment]
`glob` is a dependency for tern. please try to reinstall the package or delete `node_modules` inside the package folder `.atom/packages/atom-ternjs` and do a fresh apm install.

**Comment by dandonmesvak** [comment]
I did ```npm install``` inside the ```~/.atom/packages/atom-ternjs/``` folder. It fixed my problem. :)
