### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by bekos** [tststs/atom-ternjs#183]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.11.3

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON

```
At /Users/newzuluimac/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:38

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Client.module.exports.Client.update (/Users/newzuluimac/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:38:5)
    at Type.module.exports.Type.queryType (/Users/newzuluimac/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:126:21)
    at Manager.onDidChangeCursorPosition (/Users/newzuluimac/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:309:17)
    at later (/Users/newzuluimac/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:724:25)
```

### Commands

```
  9x -0:28.5.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:25.8.0 core:select-right (atom-text-editor.editor.is-focused)
  2x -0:23.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22.1.0 core:move-right (atom-text-editor.editor.is-focused)
 13x -0:19.9.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:13.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:11.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:11.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:10.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:08.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:02.5.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "editor"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false
  },
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-pair, v2.0.10
atom-ternjs, v0.11.3
atom-typescript, v7.14.2
color-picker, v2.0.14
editorconfig, v1.2.2
emmet, v2.3.17
file-icons, v1.6.13
fonts, v1.0.0
highlight-line, v0.11.0
language-jade, v0.6.2
linter, v1.11.3
minimap, v4.18.0
minimap-find-and-replace, v4.4.0
monokai, v0.18.0
pigments, v0.19.3
project-ring, v0.36.0
react, v0.12.10
repository-file-actions, v0.7.0
symbols-tree-view, v0.10.1
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by tststs** [comment]
Shouldn't happen here.
Are you able to provide a sample file witch causes the issue?

Greetings.

**Comment by danwkennedy** [comment]
I get the same. I upgraded to the newest version of the package and every time I make a change to a file it hangs and then throws a few seconds later.

**Comment by tststs** [comment]
Please provide the .tern-project config and a sample to reproduce the issue (if possible).
I tried several projects, configurations on OSX and Windows and never faced the issue. So there is no way for me to reproduce the issue.

Greetings.
