### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Olmer1st** [tststs/atom-ternjs#184]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.11.3

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of undefined

```
At /home/vadim/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:259

TypeError: Cannot read property 'type' of undefined
    at /home/vadim/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:259:37
    at analyzeAll (/home/vadim/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:387:15)
    at Object.done (/home/vadim/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:344:7)
    at Object.signal (/home/vadim/.atom/packages/atom-ternjs/node_modules/tern/lib/signal.js:28:49)
    at Object.signal.mixin.finishAsyncAction (/home/vadim/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:187:38)
    at /home/vadim/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:313:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

### Commands

```
     -0:00.6.0 tern:references (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/media/vadim/Data/Projects",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-autocomplete-php, v0.18.1
atom-html-preview, v0.1.13
atom-jade, v0.3.0
atom-ternjs, v0.11.3
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.2.3
color-picker, v2.0.14
emmet, v2.3.17
file-icons, v1.6.13
highlight-line, v0.11.0
highlight-selected, v0.11.1
javascript-snippets, v1.0.0
linter, v1.11.3
linter-csslint, v1.1.0
minimap, v4.18.0
node-debugger, v1.3.0
php-cs-fixer, v2.5.1
php-debug, v0.1.4
pigments, v0.19.3
pretty-json, v0.4.1
python-tools, v0.6.7
remote-edit, v1.8.23

# Dev
No dev packages
```

**Comment by bbaaxx** [comment]
This is happening to me when opening files on folders more than 2 levels deep on my project.
I explicitly added my files to the .tern-project.json using this:

```
"loadEagerly": [
    "src/**/*.js"
  ]
```

And seems to be working fine with this workaround.
