### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by nfcampos** [tststs/atom-ternjs#187]
1. as soon as i type something in a .jsx (react) file this happens

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.12.1

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of null

```
At /Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1051

TypeError: Cannot read property 'type' of null
    at patternName (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1051:13)
    at Array.map (native)
    at patternName (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1054:65)
    at Object.exports.scopeGatherer.walk.make.Function (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1090:23)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.FunctionDeclaration (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:246:10)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.NewExpression.base.CallExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:331:5)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.MemberExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:335:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.NewExpression.base.CallExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:329:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.MemberExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:335:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.NewExpression.base.CallExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:329:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.exports.scopeGatherer.walk.make.Function (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1106:7)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.FunctionDeclaration (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:246:10)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.MethodDefinition.base.Property (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:368:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.ObjectExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:303:5)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.BinaryExpression.base.LogicalExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:317:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.BinaryExpression.base.LogicalExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:316:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.ReturnStatement.base.YieldExpression (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:212:22)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.Program.base.BlockStatement (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:180:5)
    at Object.exports.scopeGatherer.walk.make.BlockStatement (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1111:17)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.exports.scopeGatherer.walk.make.Function (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1106:7)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.FunctionDeclaration (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:246:10)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.MethodDefinition.base.Property (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:368:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.exports.scopeGatherer.walk.make.ClassDeclaration (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1139:9)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.skipThrough (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.base.Program.base.BlockStatement [as Program] (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:180:5)
    at c (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35)
    at Object.recursive (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:69:5)
    at Object.exports.analyze (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1713:10)
    at /Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:281:13
    at Object.exports.withContext (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:865:18)
    at analyzeFile (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:278:11)
    at analyzeAll (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:383:11)
    at doRequest (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:246:7)
    at Object.signal.mixin.request (/Users/nuno/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:161:7)
    at Server.respond (/Users/nuno/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:425:17)
    at IncomingMessage.<anonymous> (/Users/nuno/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:95:16)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
     -0:07.2.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pep8",
      "emmet-simplified",
      "minimap",
      "minimap-codeglance",
      "minimap-git-diff",
      "react-snippets"
    ],
    "packagesWithKeymapsDisabled": [
      "terminal-plus",
      "markdown-writer"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "atom-ternjs": {
    "useSnippets": true,
    "displayAboveSnippets": true
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.3
atom-dark-fusion-syntax, v1.1.0
atom-ternjs, v0.12.1
color-picker, v2.0.14
file-icons, v1.6.13
git-diff-details, v0.21.0
keyboard-localization, v1.4.11
language-babel, v2.6.2
linter, v1.11.3
linter-eslint, v5.2.6
pigments, v0.19.3
terminal-plus, v0.14.5
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by 2c2c** [comment]
I've been doing a lot of work for the past week and only just started getting a similar error message (similar line number in infer.js)

```
TypeError: Cannot read property 'name' of undefined
    at addVar (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1048:34)
    at Object.exports.scopeGatherer.walk.make.ImportDeclaration (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1153:9)
    at c (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\node_modules\acorn\dist\walk.js:68:35)
    at Object.skipThrough (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\node_modules\acorn\dist\walk.js:169:3)
    at c (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\node_modules\acorn\dist\walk.js:68:35)
    at Object.base.Program.base.BlockStatement [as Program] (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\node_modules\acorn\dist\walk.js:180:5)
    at c (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\node_modules\acorn\dist\walk.js:68:35)
    at Object.recursive (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\node_modules\acorn\dist\walk.js:69:5)
    at Object.exports.analyze (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1713:10)
    at C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\tern.js:281:13
    at Object.exports.withContext (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:865:18)
    at analyzeFile (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\tern.js:278:11)
    at analyzeAll (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\tern.js:383:11)
    at doRequest (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\tern.js:246:7)
    at Object.signal.mixin.request (C:\Users\craig\.atom\packages\atom-ternjs\node_modules\tern\lib\tern.js:161:7)
    at Server.respond (C:/Users/craig/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:425:17)
    at IncomingMessage.<anonymous> (C:/Users/craig/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:95:16)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

Im on windows 8 atom 1.3.2 tern 12.1. happens when it tries to autocomplete names of vars/functions i think
