### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by neonsamurai** [tststs/atom-ternjs#19]
I currently can't reproduce this reliably. I do realize that this is of somewhat limited help :/

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.4.15

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/timjagodzinski/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:112

TypeError: Cannot read property 'replace' of undefined
  at Provider.module.exports.Provider.fixCompletion (/Users/timjagodzinski/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:112:28)
  at Object.<anonymous> (/Users/timjagodzinski/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:75:36)
  at Object.<anonymous> (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:3251:33)
  at fire (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:3206:7)
  at Object.<anonymous> (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:3258:41)
  at fire (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:3206:7)
  at done (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:8259:14)
  at XMLHttpRequest.<anonymous> (/Users/timjagodzinski/.atom/packages/atom-ternjs/node_modules/jquery/dist/jquery.js:8600:9)

```

### Commands

```
     -0:41.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:41.0 snippets:expand (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:41.0 editor:indent (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:35.0 docblockr:parse-tab (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:35.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:27.9 docblockr:parse-tab (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:27.9 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:09.6 docblockr:parse-tab (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:09.6 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:08.3 docblockr:parse-tab (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:08.3 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:06.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:06.0 editor:newline (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:02.3 core:backspace (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:01.6 docblockr:parse-tab (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
     -0:01.6 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.autocomplete-active.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "meteor-api"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.3
atom-color-highlight, v3.0.6
atom-handlebars, v0.4.0
atom-jshint, v1.5.0
atom-ternjs, v0.4.15
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.3
docblockr, v0.5.8
file-types, v0.3.0
filetype-color, v0.1.3
git-control, v0.1.8
jsformat, v0.7.18
language-latex, v0.4.1
language-log, v0.2.0
language-spacebars, v0.2.2
linter-handlebars, v0.1.1
pretty-json, v0.3.2
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by ponychicken** [comment]
Regression from latest release I think

**Comment by ponychicken** [comment]
(I also get a lot)

**Comment by tststs** [comment]
could not reproduce it but the latest version hopefully fixes the problem. Please reopen the ticket if the problem still occurs or something other behaves wrong.

thx
tststs

**Comment by nkt** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.5.14

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/nkt/.atom/packages/atom-ternjs/lib/atom-ternjs-helper.coffee:91

TypeError: Cannot read property 'replace' of undefined
  at Helper.module.exports.Helper.formatTypeCompletion (/Users/nkt/.atom/packages/atom-ternjs/lib/atom-ternjs-helper.coffee:91:16)
  at Object.<anonymous> (/Users/nkt/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:69:39)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3251:33)
  at fire (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3206:7)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3258:41)
  at fire (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3206:7)
  at done (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8259:14)
  at XMLHttpRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8600:9)

```

### Commands

```
     -0:59.8 editor:newline (atom-text-editor.editor)
  8x -0:59.1 core:backspace (atom-text-editor.editor)
     -0:56.2 editor:newline (atom-text-editor.editor)
     -0:51.3 autocomplete:toggle (atom-text-editor.editor)
  2x -0:50.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:50.5 core:cancel (atom-text-editor.editor.mini)
 21x -0:49.9 core:backspace (atom-text-editor.editor)
     -0:46.7 core:save (atom-text-editor.editor)
  2x -0:36.3 editor:newline (atom-text-editor.editor)
  2x -0:35.1 core:backspace (atom-text-editor.editor)
     -0:31.6 autocomplete:toggle (atom-text-editor.editor)
     -0:30.6 core:backspace (atom-text-editor.editor.mini)
  2x -0:30.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:30.0 core:cancel (atom-text-editor.editor.mini)
  8x -0:29.8 core:backspace (atom-text-editor.editor)
  2x -0:04.0 editor:newline (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "oceanic-next"
    ],
    "ignoredNames": [
      ".idea"
    ],
    "projectHome": "/Users/nkt/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.14
autocomplete-paths, v1.0.2
autocomplete-plus, v2.8.0
color-picker, v1.6.0
file-icons, v1.5.2
linter, v0.12.0
oceanic-next, v0.1.1
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by BuZZ-dEE** [comment]
Today I had this issue too.

**Comment by smddzcy** [comment]
Just had this issue.

**Comment by tststs** [comment]
The issue points to a file that does not exist anymore.
Please open another issue.

**Comment by Cafune** [comment]
File might not exist, but the issue still does.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.17.0


### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:103

TypeError: Cannot read property 'replace' of undefined
    at Client.update (/Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:103:65)
    at Type.queryType (/Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-type.js:218:20)
    at Manager.onDidChangeCursorPosition (/Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:278:12)
    at later (/Users/atrager/.atom/packages/atom-ternjs/node_modules/underscore/underscore.js:724:25)
```

### Commands

```
     -0:28.7.0 application:new-file (input.hidden-input)
     -0:28.1.0 core:paste (input.hidden-input)
     -0:26.6.0 grammar-selector:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "coffee-compile"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "nord-atom-syntax"
    ],
    "warnOnLargeFileLimit": 5
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (active)
advanced-open-file, v0.16.5 (inactive)
atom-jade, v0.3.0 (active)
atom-minify, v0.8.0 (active)
atom-ternjs, v0.17.0 (active)
autoclose-html, v0.23.0 (active)
autocompiler-pug-jade, v2.0.1 (active)
busy, v0.7.0 (active)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.4 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.13 (active)
filesize, v2.0.4 (active)
gibber, v0.1.3 (inactive)
gulp-control, v0.5.0 (inactive)
highlight-line, v0.12.0 (active)
jshint, v1.8.6 (active)
language-pug, v0.0.19 (active)
linter, v1.11.21 (active)
linter-htmlhint, v1.3.1 (active)
linter-pug-lint, v0.2.0 (active)
linter-scss-lint, v3.0.4 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.8 (active)
minimap-cursorline, v0.2.0 (active)
nord-atom-syntax, v0.6.0 (active)
open-recent, v5.0.0 (active)
pigments, v0.39.0 (active)
sass-autocompile, v0.13.2 (active)
sort-lines, v0.14.0 (inactive)
tidalcycles, v0.8.5 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
