### ISSUE TITLE
Uncaught ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by duanzheng** [tststs/atom-ternjs#214]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Unknown Windows Version
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.9.1

### Stack Trace

Uncaught ReferenceError: fetch is not defined

```
At /C:/Users/Administrator/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:188

ReferenceError: fetch is not defined
  at Client.module.exports.Client.post (C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs-client.coffee:127:5)
  at Client.module.exports.Client.update (C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs-client.coffee:66:6)
  at Type.module.exports.Type.queryType (C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs-type.coffee:130:21)
  at C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:170:17
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\text-editor.js:1599:27)
  at Selection.module.exports.Selection.markerDidChange (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\selection.js:909:21)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\selection.js:43:24
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\marker.js:270:27)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\marker.js:65:26
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\text-buffer\lib\marker.js:401:20)
  at Marker.module.exports.Marker.update (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\text-buffer\lib\marker.js:346:12)
  at Marker.module.exports.Marker.setHeadPosition (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\text-buffer\lib\marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\marker.js:175:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\marker.js:185:19)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\cursor.js:84:31
  at Cursor.module.exports.Cursor.changePosition (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\cursor.js:696:7)
  at Cursor.module.exports.Cursor.setScreenPosition (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\cursor.js:82:19)
  at Cursor.module.exports.Cursor.moveLeft (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\cursor.js:274:21)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\text-editor.js:1429:23
  at TextEditor.module.exports.TextEditor.moveCursors (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\text-editor.js:1593:9)
  at TextEditor.module.exports.TextEditor.moveLeft (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\text-editor.js:1428:19)
  at BracketMatcher.module.exports.BracketMatcher.insertText (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\bracket-matcher\lib\bracket-matcher.js:116:21)
  at TextEditor.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\bracket-matcher\lib\bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertText] (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:76:20)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\text-editor-component.js:435:35)
  at HTMLDivElement.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\src\text-editor-component.js:3:61)

```

### Commands

```
     -4:48.2.0 core:copy (atom-text-editor.editor.is-focused)
     -4:39.9.0 grammar-selector:show (atom-text-editor.editor)
  2x -4:33.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:27.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:24.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:26.3.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:13.4.0 core:backspace (atom-text-editor.editor.is-focused)
 10x -0:12 core:save (atom-text-editor.editor.is-focused)
     -0:07.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-ternjs, v0.9.1
file-icons, v1.6.18

# Dev
No dev packages
```

**Comment by duanzheng** [comment]
this is my .tern-project

{
  "ecmaVersion": 6,
  "libs": [
    "jquery"
  ],
  "loadEagerly": [
    "js/**/*.js"
  ]
}

**Comment by tststs** [comment]
Please update your Atom editor and the atom-ternjs package.
