### ISSUE TITLE
Ternjs not working after upgrade to 0.14.1 when open an old folder with .tern-project file

### ISSUE THREAD

**Issue by grissom1** [tststs/atom-ternjs#229]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.14.1

### Stack Trace

Uncaught TypeError: Cannot read property 'request' of undefined

```
At /C:/Users/Wang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:204

TypeError: Cannot read property 'request' of undefined
    at Client.module.exports.Client.post (file:///C:/Users/Wang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:143:30)
    at Client.module.exports.Client.files (file:///C:/Users/Wang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:137:6)
    at Client.module.exports.Client.update (file:///C:/Users/Wang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:67:6)
    at Type.module.exports.Type.queryType (file:///C:/Users/Wang/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:126:21)
    at Manager.onDidChangeCursorPosition (C:/Users/Wang/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:332:17)
    at later (C:\Users\Wang\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:724:25)
```

### Commands

```
     -2:04.4.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -1:59.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:54.4.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:45.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:44.7.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:44.7.0 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:44.7.0 editor:indent (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 20x -1:43.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:35.2.0 settings-view:open (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -1:14.2.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:03.3.0 tree-view:move (span.name.icon.icon-file-text)
     -0:59.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -0:53.4.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:24.5.0 atom-ternjs:openConfig (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:08.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter-jshint",
      "terminal-plus"
    ],
    "themes": [
      "nucleus-dark-ui",
      "monokai-seti"
    ]
  },
  "atom-ternjs": {
    "displayAboveSnippets": true,
    "documentation": false,
    "origins": false,
    "urls": false,
    "useSnippets": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-alignment, v0.12.1
atom-ternjs, v0.14.1
atom-typescript, v8.9.1
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
emmet, v2.4.3
file-icons, v1.7.8
highlight-selected, v0.11.2
language-babel, v2.18.5
linter, v1.11.4
linter-eslint, v7.2.1
linter-flake8, v1.13.0
linter-htmlhint, v1.1.4
merge-conflicts, v1.4.2
minimap, v4.23.2
minimap-git-diff, v4.3.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
monokai-seti, v0.7.0
nucleus-dark-ui, v0.7.20
pigments, v0.26.0
project-manager, v2.9.7
react, v0.15.0
Sublime-Style-Column-Selection, v1.5.1
symbol-gen, v1.3.0
symbols-tree-view, v0.12.0
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by tststs** [comment]
Is it the case, that there was a previous installation of nuclide?
If so, even if you uninstall nuclide `atom-ternjs` will not work.

you need to reinstall atom and all packages.

**Comment by awilkins** [comment]
Does this still cause problems? Does installing Nuclide break atom-ternjs permanently until you nuke your package folder?

**Comment by grissom1** [comment]
Didn't get a change to try out yet. But stay at 0.13.2 has no problem so far. It might be version related issue.
