### ISSUE TITLE
child process error: Error: channel closed

### ISSUE THREAD

**Issue by jamr-ron** [tststs/atom-ternjs#238]
I keep getting this error (using Mac OS X) so I have had to disable it. Love the plugin, hoping a fix comes soon. 

More info: http://stackoverflow.com/questions/37421204/child-process-error-error-channel-closed-node-atom/37737769#37737769

Thanks!

**Comment by tststs** [comment]
A bit more information is needed, since this will not give me a hint what is causing the issue.

e.g:
- installed packages
- atom version
- plugin version
- node version
- example project causing the issue

a.s.o.

**Comment by A2K** [comment]
I am get the same error while editing files that use ECMAScript 6 syntax.

**Comment by A2K** [comment]
I am getting the same error when editing files that use ECMAScript 6 syntax. Restarting Ternjs server helps for a few hours.

Atom version: 1.10.2

List of installed community packages:
```
Community Packages (22)
├── activate-power-mode@0.8.1
├── api-docs@0.0.6
├── atom-beautify@0.29.12
├── atom-html-preview@0.1.22
├── atom-ternjs@0.15.0
├── color-picker@2.2.2
├── es6-javascript@1.0.0
├── fonts@1.6.0
├── git-plus@5.17.1
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── hyperclick@0.0.38
├── js-hyperclick@1.5.0
├── language-babel@2.40.0
├── language-glsl@2.0.1
├── minimap@4.25.0
├── minimap-autohide@0.10.1
├── minimap-codeglance@0.4.5
├── minimap-cursorline@0.2.0
├── minimap-git-diff@4.3.1
├── tab-switcher@1.5.3
└── vim-mode-plus@0.56.0
```

.tern-project
```
{
  "ecmaVersion": 6,
  "libs": [
    "browser",
    "jquery"
  ],
  "loadEagerly": [
    "js/three.js"
  ],
  "plugins": {}
}
```

I can't provide an example project at the moment; just wanted to report the problem.

**Comment by oNaiPs** [comment]
I have the same problem with OSX

**Comment by Jore** [comment]
I'm having the same issue.

**Comment by ronjouch** [comment]
Same issue. Or not, for me the error pops only at app **shutdown**.

* Log:

```
 ~ mkdir testproject
 ~ cd testproject
 ~ atom .  
App load time: 415ms
### IN APP HERE, QUITTING AFTER TWO SECONDS DOING NOTHING ###
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at process.<anonymous> (/home/ronj/.atom/packages/atom-ternjs/lib/atom-ternjs-server-worker.js:119:11)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:244:26)
```

* Installed packages and atom-ternjs version

```
Community Packages (29) /home/ronj/.atom/packages
├── atom-ternjs@0.15.0
├── autocomplete-modules@1.6.3
├── autocomplete-python@1.8.6
├── docblockr@0.8.5
├── git-plus@5.17.1
├── git-time-machine@1.5.3
├── highlight-selected@0.11.2
├── language-batch@0.3.3
├── language-docker@1.1.7
├── language-elm@1.5.0
├── linter@1.11.16
├── linter-elm-make@0.17.7
├── linter-eslint@7.3.2
├── linter-flake8@1.13.4
├── linter-shellcheck@1.3.0
├── merge-conflicts@1.4.4
└── pigments@0.35.0
```
* Atom version & node version

```
 ~/testproject atom --version
Atom    : 1.11.0-beta5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

* Example project causing the issue:  
As you saw, even an empty project/directory will do.

**Comment by aysark** [comment]
Same issue- i'm on windows 10- on mac i don't seem to get it.

Its pretty spammy, seems to trigger almost on key up.  Disabled atom-ternjs cause of it.

```
Community Packages (32) 
├── activate-power-mode@1.0.2
├── atom-beautify@0.29.13
├── atom-html-preview@0.1.22
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.3.6
├── atom-monokai@0.10.4
├── atom-react-preview@2.0.0
├── atom-ternjs@0.15.0
├── atom-typescript@10.1.8
├── autoclose-html@0.23.0
├── color-picker@2.2.2
├── docblockr@0.8.7
├── double-tag@0.4.0
├── fold-lines@0.2.1
├── git-plus@5.18.0
├── highlight-selected@0.11.2
├── javascript-snippets@1.2.1
├── linter@1.11.18
├── linter-csslint@1.3.3
├── linter-eslint@8.0.0
├── linter-tidy@2.2.1
├── merge-conflicts@1.4.4
├── minimap@4.25.0
├── monokai@0.18.0
├── pigments@0.37.0
├── react@0.16.1
├── seti-syntax@1.0.1
├── seti-ui@1.3.2
├── sort-lines@0.14.0
├── sync-settings@0.7.2
├── terminal-plus@0.14.5
└── vim-mode@0.65.1

└── (empty)
```

**Comment by A2K** [comment]
So it looks like the worker thread sometimes runs into a state when it can't receive messages but does not exit. The error message discussed here appears on attempt to send a message to a worked which is stuck in that state.

It may be a bug in the Server class. Or something may freeze the worker thread. It's not easy to debug. 

Here is my fork with automatic restart of the worker thread on error: https://github.com/A2K/atom-ternjs/commits/master

I am not sure if it is a good solution to this problem, please tell me what you think.

**Comment by kaeyleo** [comment]
I have same issue on mac osx 10.11.6

**Comment by RonItelman** [comment]
It definitely has been happening a lot less since your update - thanks!

**Comment by m3talstorm** [comment]
Starts getting really spammy, error comes up on every keypress (attempt to validate/autocomplete/etc?) filling up the screen. I my muscle memory now presses escape (to close them all) every few seconds of typing 👎
