### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by cfv1984** [tststs/atom-ternjs#24]
1. Choose to "refactor" a single variable
2. Get this below:

**Atom Version**: 0.169.0
**System**: linux 3.13.0-39-generic
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.4.8

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs-reference.coffee:44

TypeError: undefined is not a function
  at Reference.module.exports.Reference.findReference (/home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs-reference.coffee:44:25)
  at atom-text-editor.disposables.push.atom.commands.add.tern:references (/home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs-reference.coffee:27:8)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:27.1 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:27.1 snippets:expand (atom-text-editor.editor.is-focused)
     -0:27.1 editor:indent (atom-text-editor.editor.is-focused)
     -0:26.3 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -0:25.6 core:move-down (atom-text-editor.editor.is-focused)
  6x -0:24.5 core:cut (atom-text-editor.editor.is-focused)
     -0:23.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:22.7 core:cut (atom-text-editor.editor.is-focused)
     -0:22.1 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:11.1 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.1 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.2 core:move-down (atom-text-editor.editor.mini)
     -0:01.7 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:01.7 core:cancel (atom-text-editor.editor.mini)
     -0:00.0 refactor:rename (atom-text-editor.editor.is-focused)
     -0:00.0 tern:references (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
atom-ternjs, v0.4.8
autocomplete-plus, v1.1.0
color-picker, v1.2.6
esformatter, v1.2.0
js-refactor, v0.3.0
language-less, v0.24.0
linter, v0.9.1
minimap, v3.5.4
project-manager, v1.14.1
refactor, v0.4.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by tststs** [comment]
pls update atom and atom-ternjs.
atom is currently at 0.179 and atom-ternjs at 0.4.17.

If the problem still occurs after update, post another stack trace.

thx
tststs

**Comment by cfv1984** [comment]
Curiously enough, I got a new one. 

```javascript
/home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:73
Hide Stack Trace
TypeError: Cannot read property 'provide' of undefined
  at AtomTernInitializer.activatePackage (/home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:73:45)
  at AtomTernInitializer.init (/home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:76:6)
  at /home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:104:10
  at stdout (/home/cfv/.atom/packages/atom-ternjs/lib/atom-ternjs-server.coffee:16:7)
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)
```

**Comment by tststs** [comment]
Please feel free to reopen the ticket, if this still is a problem.

**Comment by sidhantgoel** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.5.24

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\sidhant\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:96

TypeError: undefined is not a function
  at Manager.module.exports.Manager.setActiveServerAndClient (C:\Users\sidhant\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:96:43)
  at C:\Users\sidhant\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:36:8
  at Emitter.module.exports.Emitter.emit (C:\Users\sidhant\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Project.module.exports.Project.addPath (C:\Users\sidhant\AppData\Local\atom\app-0.198.0\resources\app.asar\src\project.js:274:29)
  at C:\Users\sidhant\AppData\Local\atom\app-0.198.0\resources\app.asar\src\atom.js:848:41
  at EventEmitter.<anonymous> (C:\Users\sidhant\AppData\Local\atom\app-0.198.0\resources\app.asar\src\atom.js:409:16)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -7:07.3.0 gulp-control:toggle (atom-text-editor.editor.is-focused)
     -6:08.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:06.3.0 core:save (atom-text-editor.editor.is-focused)
     -5:56.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:55 core:save (atom-text-editor.editor.is-focused)
     -1:33.2.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:04.7.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:48.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:48.8.0 core:delete (atom-text-editor.editor.mini.is-focused)
  3x -0:48.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:07.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.1
atom-terminal-panel, v4.4.3
atom-ternjs, v0.5.24
autocomplete-html, v0.7.1
autocomplete-plus, v2.13.1
autocomplete-plus-python-jedi, v0.3.2
color-picker, v1.7.0
gulp-control, v0.3.3
linter, v0.12.2
linter-coffeelint, v0.2.3
linter-csslint, v0.0.12
linter-javac, v0.1.3
linter-jshint, v0.1.4
linter-pylint, v0.2.1
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
linter-xmllint, v0.0.5
local-history, v3.1.0
minimap, v4.8.0
project-manager, v1.15.5
travis-ci-status, v0.14.0

# Dev
No dev packages
```

**Comment by malko** [comment]
same problem here

**Comment by sivid** [comment]
[Enter steps to reproduce below:]

1. select code from atom editor pane A
2. select all from atom editor pane B
3. paste

**Atom Version**: 0.200.0
**System**: linux 3.8.11
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.2


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app.asar/src/pane.js:759

TypeError: undefined is not a function
    at /home/sivid/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:303:88
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:967:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:567:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:523:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:506:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:585:35)
    at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:314:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
```

### Commands

```
     -2:22.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:21.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:21.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:20.4.0 find-and-replace:show (ul.list-inline.tab-bar.inset-panel)
     -2:19.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:18.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:48.7.0 core:copy (atom-text-editor.editor.is-focused)
     -1:47.8.0 find-and-replace:show (ul.list-inline.tab-bar.inset-panel)
     -1:47.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:45.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.7.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.6.2
highlight-selected, v0.9.3
minimap, v4.9.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.2.3

# Dev
No dev packages
```

**Comment by despairblue** [comment]
happens when editing a file outside of the project root (for example editing project managers project.cson file)


**Atom Version**: 0.206.0
**System**: linux 3.14.43-2-lts
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.4


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app.asar/src/pane.js:759

TypeError: undefined is not a function
  at /home/despairblue/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:173:49
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1020:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:578:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:08.4.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.7.0 project-manager:edit-projects (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop",
      "navigate",
      "atom-zeal",
      "compare-files"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true,
    "ignoredNames": [
      "SCENE"
    ]
  },
  "atom-ternjs": {
    "coffeeScript": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-alignment, v0.12.1
atom-beautify, v0.27.10
atom-color-highlight, v3.0.9
atom-fuzzy-grep, v0.2.0
atom-ternjs, v0.6.4
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
bug-report, v0.7.0
color-picker, v2.0.4
docblockr, v0.7.2
editorconfig, v1.0.0
file-icons, v1.5.7
git-log, v0.4.1
go-plus, v3.3.11
grammar-token-limit, v0.1.1
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-dockerfile, v0.1.0
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.0.0
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.12.0
language-tss, v0.4.0
latex, v0.24.1
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-htmlhint, v0.0.16
linter-js-standard, v0.2.5
linter-js-yaml, v1.0.1
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.8
markdown-scroll-sync, v0.4.0
notifications, v0.49.0
package-sync, v0.2.0
pdf-view, v0.22.0
project-manager, v1.15.8
react, v0.12.0
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by despairblue** [comment]
ah, this seems to be a different issue
