### ISSUE TITLE
Uncaught TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by mzlogin** [tststs/atom-ternjs#240]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.14.1

### Stack Trace

Uncaught TypeError: Cannot read property 'request' of undefined

```
At /C:/Users/mazhuang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:204

TypeError: Cannot read property 'request' of undefined
    at Client.module.exports.Client.post (file:///C:/Users/mazhuang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:143:30)
    at Client.module.exports.Client.files (file:///C:/Users/mazhuang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:137:6)
    at Client.module.exports.Client.update (file:///C:/Users/mazhuang/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:67:6)
    at Type.module.exports.Type.queryType (file:///C:/Users/mazhuang/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:126:21)
    at Manager.onDidChangeCursorPosition (C:/Users/mazhuang/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:332:17)
    at later (C:\Users\mazhuang\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:724:25)
```

### Commands

```
     -5:38.6.0 tree-view:remove-project-folder (div.header.list-item)
     -4:45 application:add-project-folder (atom-text-editor.editor.mini.is-focused)
     -4:29 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -3:56.7.0 tree-view:add-folder (div.header.list-item)
     -3:49 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:42.1.0 tree-view:add-file (div.header.list-item)
     -3:38.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 31x -3:09.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:54.6.0 atom-ternjs:restart (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "vim-mode",
      "atom-terminal-panel"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.14.1
autocomplete-paths, v1.0.2
linter, v1.11.10
symbols-tree-view, v0.13.2

# Dev
No dev packages
```

**Comment by marszall87** [comment]
Also experiencing this.

Atom Version: 1.8.0
System: macOS 10.11.5
Thrown From: atom-ternjs package, v0.14.2

**Comment by tststs** [comment]
is this still an issue with 0.15?
Since the coffee file does not exist anymore, pls open another issue

**Comment by noderat** [comment]
[Enter steps to reproduce below:]
1. Highlighted config in `const config = require('../config');`
2. Selected Find Definition

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: "Arch Linux"
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.15.0


### Stack Trace

Uncaught TypeError: Cannot read property 'request' of undefined

```
At /home/noderat/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:247

TypeError: Cannot read property 'request' of undefined
    at Client.post (/home/noderat/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:247:35)
    at Client.definition (/home/noderat/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:208:17)
    at atom-text-editor.<anonymous> (/home/noderat/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:435:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1127:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:341:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -2:43.6.0 atom-ternjs:openConfig (atom-text-editor.editor.is-focused)
     -2:20.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-seti-syntax.theme-atom-dark-ui)
     -1:30.1.0 atom-ternjs:listFiles (atom-text-editor.editor.is-focused)
     -1:24.4.0 atom-ternjs:restart (atom-text-editor.editor.is-focused)
     -1:21.4.0 atom-ternjs:openConfig (atom-text-editor.editor.is-focused)
     -1:09.2.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -1:03.7.0 atom-ternjs:openConfig (ul.list-inline.tab-bar.inset-panel)
     -0:05.1.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:00.1.0 atom-ternjs:definition (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "background-tips",
      "symbol-gen",
      "symbols-tree-view",
      "whitespace",
      "merge-conflicts",
      "atom-beautify",
      "welcome"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-ternjs, v0.15.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-nunjucks, v0.5.0 (active)
blame, v0.10.0 (inactive)
docker, v0.7.0 (inactive)
editorconfig, v2.0.4 (active)
file-icons, v1.7.24 (active)
fonts, v1.7.0 (active)
git-plus, v5.23.3 (active)
highlight-selected, v0.11.2 (active)
json-schema, v0.1.15 (active)
language-babel, v2.47.0 (active)
language-docker, v1.1.7 (active)
language-ejs, v0.4.0 (active)
language-gitignore, v0.3.0 (active)
language-ini, v1.16.0 (active)
language-json5, v1.1.0 (active)
language-nunjucks, v4.1.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-shellcheck, v1.4.1 (active)
linter-xmllint, v1.3.6 (active)
merge-conflicts, v1.4.4 (inactive)
node_modules, vundefined (active)
pigments, v0.37.0 (active)
project-manager, v3.3.3 (active)
seti-syntax, v1.0.1 (active)
sort-lines, v0.14.0 (inactive)
symbol-gen, v1.3.1 (inactive)
sync-settings, v0.7.2 (active)
tool-bar, v1.0.1 (active)
tree-view, v0.211.1 (active)
tree-view-autoresize, v1.3.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (active)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
