### ISSUE TITLE
Uncaught TypeError: Type is not a constructor

### ISSUE THREAD

**Issue by mingjunyang** [tststs/atom-ternjs#249]
[Enter steps to reproduce below:]

1. when I update  atom-ternjs 0.14.2 -> 0.15.0 
 
**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.14.2

### Stack Trace

Uncaught TypeError: Type is not a constructor

```
At /Users/xxxxxx/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:305

TypeError: Type is not a constructor
    at Manager.onDidChangeCursorPosition (/Users/xxxxxx/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:305:75)
    at later (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:724:25)
```

### Commands

```
  2x -9:50.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:45.8.0 core:paste (atom-text-editor.editor.is-focused)
     -9:43.7.0 core:save (atom-text-editor.editor.is-focused)
     -9:43.6.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -9:43.2.0 core:save (atom-text-editor.editor.is-focused)
  6x -8:59.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:56.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:43.6.0 tree-view:remove (span.name.icon.icon-file-text)
  4x -1:30.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:25.8.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -1:25.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:42.8.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:16.5.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:16 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-erlang",
      "autocomplete-go",
      "builder-go",
      "go-config",
      "go-debug",
      "go-get",
      "go-plus",
      "gofmt",
      "gometalinter-linter",
      "gorename",
      "activate-power-mode",
      "language-julia",
      "tester-go",
      "vim-mode",
      "vim-mode-plus",
      "angular2-snippets",
      "autocomplete-python",
      "language-erlang",
      "language-scala",
      "linter-gcc",
      "linter-shellcheck",
      "python-autopep8",
      "navigator-godef",
      "python-isort",
      "python-tools",
      "jshint",
      "language-babel",
      "react-es6-snippets",
      "react-snippets",
      "language-javascript-jsx"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.8.1 (inactive)
angular2-snippets, v0.3.0 (inactive)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.10 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-format-lua, v0.1.5 (inactive)
atom-material-syntax, v0.4.6 (active)
atom-material-ui, v1.3.5 (active)
atom-miku, v2.2.5 (inactive)
atom-ternjs, v0.14.2 (active)
atom-typescript, v10.1.6 (active)
autoclose-html, v0.23.0 (active)
autocomplete-erlang, v1.1.2 (inactive)
autocomplete-go, v1.1.1 (inactive)
autocomplete-python, v1.8.6 (inactive)
builder-go, v1.0.1 (inactive)
css-snippets, v1.0.0 (active)
git-diff, v1.1.0 (active)
git-plus, v5.16.2 (inactive)
go-config, v1.2.3 (inactive)
go-debug, v0.1.22 (inactive)
go-get, v1.0.4 (inactive)
go-plus, v4.2.0 (inactive)
gofmt, v1.1.8 (inactive)
gometalinter-linter, v1.1.1 (inactive)
gorename, v1.0.3 (inactive)
jshint, v1.8.6 (inactive)
language-babel, v2.33.0 (inactive)
language-cmake, v0.2.0 (active)
language-erlang, v3.0.0 (inactive)
language-ini, v1.16.0 (active)
language-javascript-jsx, v0.3.7 (inactive)
language-julia, v0.6.0 (inactive)
language-lua, v0.9.11 (active)
language-nginx, v0.6.1 (active)
language-pgsql, v0.2.3 (active)
language-python, v0.45.0 (active)
language-rust, v0.4.6 (active)
language-scala, v1.1.6 (inactive)
language-ts, v1.0.2 (active)
language-viml, v1.0.0 (active)
language-vue, v0.15.1 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-erlang, v0.3.1 (active)
linter-eslint, v7.2.4 (active)
linter-gcc, v0.6.15 (inactive)
linter-lua, v1.0.2 (active)
linter-rust, v0.5.4 (active)
linter-sass-lint, v1.7.0 (active)
linter-shellcheck, v1.2.0 (inactive)
linter-tslint, v0.11.1 (active)
minimap, v4.24.7 (active)
minimap-git-diff, v4.3.1 (active)
navigator-godef, v1.0.4 (inactive)
pretty-json, v1.6.0 (active)
python-autopep8, v0.1.3 (inactive)
python-isort, v0.0.7 (inactive)
python-tools, v0.6.8 (inactive)
react, v0.16.0 (active)
react-es6-snippets, v0.3.0 (inactive)
react-snippets, v0.4.2 (inactive)
rust-api-docs-helper, v0.5.1 (active)
tester-go, v1.0.6 (inactive)
todo-show, v1.7.0 (inactive)
vim-mode, v0.65.1 (inactive)
vim-mode-plus, v0.51.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by tststs** [comment]
did you restart the editor, because the issue still shows:

`Thrown From: atom-ternjs package, v0.14.2`

**Comment by G07cha** [comment]
@tststs had a similar issue, can confirm that restarting Atom solves problem.

**Comment by mingjunyang** [comment]
@tststs I restart my atom ,the problem solves. thanks you.

**Comment by sebfindling** [comment]
RESTARTING ATOM FIXES ALL
