### ISSUE TITLE
Can not Install ternjs

### ISSUE THREAD

**Issue by yummy222** [tststs/atom-ternjs#266]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.15.0

### Stack Trace

Failed to load the atom-ternjs package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:339:15)
  at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.js:11:23)
  at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs-provider.js:11:26)
  at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ternjs\lib\atom-ternjs.js:15:27)
  at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:721:27)
  at C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:117:28
  at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
  at Package.module.exports.Package.load (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:457:14)
  at C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:402:19
  at Config.module.exports.Config.transact (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:397:19)
  at C:\Users\Administrator\AppData\Local\atom\app-1.11.2\resources\app.asar\src\atom-environment.js:759:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.0.2 (inactive)
atom-ternjs, v0.15.0 (inactive)
atomic-chrome, v0.3.0 (inactive)
emmet, v2.4.3 (inactive)
tree-view-finder, v0.2.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by tststs** [comment]
`underscore-plus` is an dependency in the package.json of this package. You may first check if there are any problems with apm while installing it.

You also may try to manually do a `$ apm install`.
$ cd ~/.atom/packages/atom-ternjs
$ apm install

**Comment by andmeics** [comment]
git clone this repository,and $npm install
