### ISSUE TITLE
TypeError: Cannot read property 'getType' of undefined

### ISSUE THREAD

**Issue by guymguym** [tststs/atom-ternjs#27]
Hi
I'm trying to use 'references' on names in my code, and in many cases I get this in the devtools console:

POST http://localhost:59821/ 400 (Bad Request)

and in the network tab I see request (removed file path):

Form Data:
{"query":{"type":"refs","file":"/removed-original-path-for-issue.js","end":{"line":61,"ch":17}}}:

Response:
TypeError: Cannot read property 'getType' of undefined

which means the server got the error, but there's no stack trace for it.
I tried to restart the server but didn't help.
it doesn't happen to all references requests, but does happen on many cases.
how can I get more debug info from the server?
thanks!

atom: 0.179.0
atom-ternjs: 0.4.18

**Comment by tststs** [comment]
Maybe an issue with the tern parser. Is there any way to provide sample code, cause i never had that issue and can't reproduce it. Normally if you query references and the cursor is not at/inside variable or property, the result is: 

400 : TernError: Not at a variable or property name.
There is a flag --verbose that can be passed to the server process. In most cases, this won't provide more information to the problem, but i will pass it by default with the next release.

thx
tststs

**Comment by guymguym** [comment]
Hi

I'm not sure if this reproduction depends on the entire project or not, but I get it on the below sample code when I select 'platform' and then do 'find references', and then I see an http failure in network tab with response - TypeError: Cannot read property 'getType' of undefined. 

In contrast when I do the same on 'BrowserWindow' it works. 

To your question - the package continues to work after these errors.

My .tern-project is also copied below.

Thanks!


```
'use strict';

var app = require('app'); // Module to control application life.
var BrowserWindow = require('browser-window'); // Module to create native browser window.

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

// This method will be called when atom-shell has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600
    });

    // and load the index.html of the app.
    mainWindow.loadUrl('http://localhost:5000');

    // Emitted when the window is closed.
    mainWindow.on('closed', function() {
        // Dereference the window object, usually you would store windows
        // in an array if your app supports multi windows, this is the time
        // when you should delete the corresponding element.
        mainWindow = null;
    });
});
```


.tern-project

```
{
  "libs": [
    "browser",
    "jquery"
  ],
  "loadEagerly": [
    "./src/**/*.js"
  ],
  "plugins": {
    "node": {},
    "angular": {},
    "complete_strings": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

**Comment by guymguym** [comment]
I updated to latest atom-ternjs (0.4.20) and now I got this new popup on error with backtrace:

```
atom-ternjs
TypeError: Cannot read property 'getType' of undefined 
at walk.simple.ObjectExpression (~/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1588:34) 
at c (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:30:18) 
at Object.skipThrough (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:163:39) 
at c (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:29:17) 
at Object.base.ThrowStatement.base.SpreadElement (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:204:5) 
at c (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:29:17) 
at Object.skipThrough (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:163:39) 
at c (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:29:17) 
at Object.base.Program.base.BlockStatement (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:171:7) 
at c (~/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/util/walk.js:29:17)
```

**Comment by tststs** [comment]
Can't reproduce it.
Is it possible to provide a example project (.tern-project, js/**, etc.) where this error occurs?
if so, maybe i can spot the error, build a workaround (till it's fixed by marijinh/tern) and report the issue.

thx
tststs

**Comment by guymguym** [comment]
sorry but I can't share my project source files

**Comment by tststs** [comment]
I'm not asking for private or sensitive data here :)
Just asking for a sample-project, where the error is reproducible.

thx
tststs

**Comment by guymguym** [comment]
sure, will try to find one

**Comment by despairblue** [comment]
Possibly related to https://github.com/marijnh/tern/issues/510 ?

**Comment by silesky** [comment]
I'm having this issue here

**Comment by silesky** [comment]
Having the same issue here:
```
import { assert } from 'chai';
import React from 'react';
import redux from 'redux';
import store from '../app/_Store.js';
import reducer from '../app/reducers/_Reducer.js';
import TestUtils from 'react-addons-test-utils';
import * from '.../app/actions/_actionCreators.js'
module.exports = function() {

  describe('* * * reducer * * *', function() {
    describe('set ticking true:', function() {
      it('store.getState()[0].ticking should return true when action: SET_TICKING_TRUE is dispatched.', function() {
      store.dispatch({ type: 'SET_TICKING_TRUE', id: 1 })
      assert.equal(store.getState()[0].ticking, true);
    });
  });
  describe('set ticking false:', function() {
    it('store.getState()[0].ticking should return false after action: SET_TICKING_FALSE is dispatched.', function() {
      store.dispatch({ type: 'SET_TICKING_FALSE', id: 1 });
      assert.equal(store.getState()[0].ticking, false);
    });
  });
  describe('startTicking', function() {
    it('store.getState()[0].ticking should return true after action: SET_TICKING_TRUE is dispatched.', function() {
      store.dispatch({ type: 'SET_TICKING_FALSE', id: 1 });
      assert.equal(store.getState()[0].ticking, false);
    });
  });
});
```
