### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Cafune** [tststs/atom-ternjs#283]
[Enter steps to reproduce below:]

1. Open a new tab
2. Set language to javascript
3. Start typing

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.16.1

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:103

TypeError: Cannot read property 'replace' of undefined
    at Client.update (/Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:103:65)
    at Type.queryType (/Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-type.js:218:20)
    at Manager.onDidChangeCursorPosition (/Users/atrager/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:279:12)
    at later (/Users/atrager/.atom/packages/atom-ternjs/node_modules/underscore/underscore.js:724:25)
```

### Commands

```
     -0:12.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:11.1.0 grammar-selector:show (atom-text-editor.editor)
     -0:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "coffee-compile"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "nord-atom-syntax"
    ],
    "warnOnLargeFileLimit": 5
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (inactive)
atom-jade, v0.3.0 (active)
atom-minify, v0.7.5 (active)
atom-ternjs, v0.16.1 (active)
autoclose-html, v0.23.0 (active)
busy, v0.7.0 (active)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.3 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.7 (active)
filesize, v2.0.0 (active)
gibber, v0.1.3 (inactive)
gulp-control, v0.5.0 (inactive)
highlight-line, v0.11.2 (active)
jshint, v1.8.6 (active)
language-pug, v0.0.19 (active)
linter, v1.11.18 (active)
linter-htmlhint, v1.3.1 (active)
linter-pug-lint, v0.2.0 (active)
linter-scss-lint, v3.0.4 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.7 (active)
minimap-cursorline, v0.2.0 (active)
nord-atom-syntax, v0.4.0 (active)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
sass-autocompile, v0.13.2 (active)
tidalcycles, v0.8.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by yourfavorite** [comment]
I am getting this as well. If I switch to Babel ES6 Javascript language I am able to work without the error.
