### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by scastette** [tststs/atom-ternjs#298]
[Enter steps to reproduce:]

1. ... Create new file.
2. ... Paste in med/large JSON.
3. ... Change file type to Javascript.

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.resolve (path.js:1148:7)
  at Manager.getProjectDir (/packages/atom-ternjs/lib/atom-ternjs-manager.js:274:46)
  at /packages/atom-ternjs/lib/atom-ternjs-manager.js:351:35
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at /app.asar/src/pane-container.js:348:27
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
  at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
  at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)

```

### Commands

```
     -2:00.2.0 core:move-left (input.hidden-input)
     -1:59.9.0 core:paste (input.hidden-input)
  2x -1:59.5.0 core:move-right (input.hidden-input)
     -1:53 editor:newline (input.hidden-input)
     -1:51.9.0 core:paste (input.hidden-input)
     -1:50.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:48.5.0 core:move-right (input.hidden-input)
     -1:48.2.0 core:backspace (input.hidden-input)
     -1:47.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -1:32.9.0 core:move-up (input.hidden-input)
  2x -1:31.8.0 core:move-down (input.hidden-input)
  4x -1:27.2.0 editor:newline (input.hidden-input)
  6x -0:58.4.0 core:backspace (input.hidden-input)
  2x -0:34.6.0 core:move-down (input.hidden-input)
  2x -0:34 core:move-right (input.hidden-input)
     -0:32.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-ternjs 0.18.1 
autocomplete-modules 1.6.7 
autoupdate-packages 1.3.1 
editorconfig 2.2.2 
nuclide 0.208.0 
term3 0.22.1 
```

**Comment by tststs** [comment]
The issue should be fixed in `0.18.2`.
Please note that there will be no autocomplete until you reopen the file after saving it since this this case isn't handled yet.
