### ISSUE TITLE
Failed to find plugin aws-sdk

### ISSUE THREAD

**Issue by AnthonyWC** [tststs/atom-ternjs#303]
Getting this error at startup with .js file:
```
Error: Cannot find module 'tern-aws-sdk'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:53:23)
    at Server.loadPlugins (/home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:399:27)
    at Server.init (/home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:75:24)
    at new Server (/home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs-server.js:49:10)
    at Manager.startServer (/home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:106:23)
    at /home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:220:43
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:329:9)
    at Manager.registerListeners (/home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:211:42)
    at Manager.activate (/home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:51:10)
    at AtomTernjs.activate (/home/antho/.atom/packages/atom-ternjs/lib/atom-ternjs.js:17:13)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:218:19)
    at /usr/share/atom/resources/app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app.asar/src/package-manager.js:581:36)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:512:17
```

I have aws-sdk installed under atom-ternjs:
```
antho@alto:~/.atom/packages/atom-ternjs% ls node_modules 
acorn            crypto-browserify  inherits   object-assign         sax                url
aws-sdk          enhanced-resolve   isarray    once                  sigmund            util-deprecate
balanced-match   errno              jmespath   path-is-absolute      string_decoder     uuid
base64-js        event-kit          lodash     process-nextick-args  tapable            wrappy
brace-expansion  fs.realpath        loophole   prr                   tern               xml2js
buffer           glob               lru-cache  punycode              tern-node-express  xmlbuilder
buffer-shims     graceful-fs        memory-fs  querystring           typescript
concat-map       ieee754            minimatch  readable-stream       underscore
core-util-is     inflight           node-uuid  resolve-from          underscore-plus
```

And there does not seem to be any apm package called tern-aws-sdk

**Comment by AnthonyWC** [comment]
As a workaround I unselected aws-sdk plugin from the project configuration.

**Comment by tststs** [comment]
The plugin may not be compatible with the tern version the package uses.
