### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by cboulanger** [tststs/atom-ternjs#309]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.2

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /Users/cboulanger/.atom/packages/atom-ternjs/lib/atom-ternjs-client.js:278

TypeError: Cannot read property 'then' of undefined
    at Client.files (/packages/atom-ternjs/lib/atom-ternjs-client.js:278:7)
    at Client.update (/packages/atom-ternjs/lib/atom-ternjs-client.js:143:17)
    at Type.queryType (/packages/atom-ternjs/lib/atom-ternjs-type.js:205:20)
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:249:31
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/app.asar/src/text-editor.js:2126:27)
    at Selection.module.exports.Selection.markerDidChange (/app.asar/src/selection.js:921:21)
    at /app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/app.asar/node_modules/text-buffer/lib/marker.js:421:20)
    at /app.asar/node_modules/text-buffer/lib/marker-layer.js:312:25
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/app.asar/node_modules/text-buffer/lib/marker-layer.js:309:39)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:34)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:842:12)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1589:26)
    at /app.asar/src/text-editor.js:1150:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2567:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2529:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1148:19)
    at TextEditor.module.exports.TextEditor.insertText (/app.asar/src/text-editor.js:1114:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/app.asar/src/text-editor-component.js:478:26)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -2:18.1.0 autocomplete-plus:confirm (input.hidden-input)
     -2:17.3.0 refactor:done (input.hidden-input)
     -2:17.3.0 docblockr:parse-enter (input.hidden-input)
  8x -2:13.4.0 core:backspace (input.hidden-input)
     -2:02.7.0 core:move-right (input.hidden-input)
     -1:19.1.0 core:copy (input.hidden-input)
     -1:10.9.0 core:paste (input.hidden-input)
  3x -0:57.8.0 core:backspace (input.hidden-input)
  3x -0:50.6.0 core:move-down (input.hidden-input)
  3x -0:49.2.0 core:move-up (input.hidden-input)
  3x -0:46.9.0 core:move-down (input.hidden-input)
     -0:34.5.0 refactor:rename (input.hidden-input)
 13x -0:21.9.0 core:backspace (input.hidden-input)
     -0:08.6.0 core:move-right (input.hidden-input)
     -0:07.0 core:move-left (input.hidden-input)
  3x -0:05.5.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.29.17 
atom-ternjs 0.18.2 
autocomplete-xml 0.9.4 
busy-signal 1.3.0 
docblockr 0.9.3 
es-navigation 0.1.5 
format-javascript-comment 0.2.2 
intentions 1.1.2 
js-refactor 0.7.5 
jsdoc-generator 0.2.3 
linter 2.1.2 
linter-jshint 3.0.3 
linter-ui-default 1.2.1 
node-debugger 1.10.1 
refactor 0.11.3 
tag 0.4.0 
todo-show 1.11.0 
```

**Comment by PixelT** [comment]
+1

**Comment by nibelune** [comment]
+1

**Comment by ktravelet** [comment]
just got this as well.

[Enter steps to reproduce:]

1. was typing out the following row:
`systemDetails.data.store.table.BLOCKED_TRANSACTIONS_BLOCKER[row[0]].push([row[1],row[2],row[3],row[4],row[5]]);`

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.3


### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /Users/i827087/.atom/packages/atom-ternjs/lib/atom-ternjs-type.js:205

TypeError: Cannot read property 'then' of undefined
    at Type.queryType (/packages/atom-ternjs/lib/atom-ternjs-type.js:205:34)
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:248:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2136:33)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:921:27)
    at /Applications/Atom.app/Contents/Resources/app/src/selection.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:421:26)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:313:31
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:310:52)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1408:40)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:873:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1599:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1160:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2577:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2539:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1158:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1124:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:480:32)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:65)
```

### Commands

```
     -1:06.8.0 core:paste (input.hidden-input)
     -1:05.0 core:move-right (input.hidden-input)
  2x -1:03.4.0 core:move-down (input.hidden-input)
     -1:02.5.0 docblockr:parse-enter (input.hidden-input)
     -1:02.5.0 editor:newline (input.hidden-input)
     -1:02.4.0 docblockr:parse-enter (input.hidden-input)
     -1:02.4.0 editor:newline (input.hidden-input)
     -0:58 core:copy (input.hidden-input)
     -0:56.4.0 core:paste (input.hidden-input)
     -0:40.5.0 core:move-right (input.hidden-input)
  9x -0:38.5.0 core:select-left (input.hidden-input)
     -0:34 core:select-right (input.hidden-input)
     -0:32.9.0 core:copy (input.hidden-input)
     -0:32.7.0 core:move-right (input.hidden-input)
  4x -0:32 core:paste (input.hidden-input)
  4x -0:24.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
docblockr 0.9.1 
docblockr 0.9.1 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
project-manager 3.3.5 
remote-edit 1.9.0 
split-diff 1.4.0 
```

**Comment by ktravelet** [comment]
FYI, I keep getting this error when copy and pasting values around.  I cant get a consistent repro though :(

**Comment by johnozbay** [comment]
I also get these whenever I copy & paste things around, but also whenever I make multiple selections (⌘+click on osx) and start typing.

**Comment by maxmoeschinger** [comment]
I get this when I make multiple selections on many strings and replace those with new strings

**Comment by OmgImAlexis** [comment]
[Enter steps to reproduce:]

1. Just started typing

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.3


### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:948

TypeError: Cannot read property 'then' of undefined
    at Client.files (/packages/atom-ternjs/lib/atom-ternjs-client.js:263:7)
    at Client.update (/packages/atom-ternjs/lib/atom-ternjs-client.js:128:17)
    at Type.queryType (/packages/atom-ternjs/lib/atom-ternjs-type.js:205:20)
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:248:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2687:31)
    at Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:914:25)
    at Selection.marker.onDidChange.e (/Applications/Atom.app/Contents/Resources/app/src/selection.js:21:45)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:428:26)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:369:18)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:144:25)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:146:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:154:25)
    at changePosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:67:16)
    at Cursor.moveDown (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:264:16)
    at moveCursors.cursor (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2532:52)
    at Array.forEach (native)
    at transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2681:31)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2680:23)
    at TextEditor.moveDown (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2532:23)
    at TextEditor.core:move-down (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:508:27)
    at HTMLElement.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:665:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:14.8.0 core:move-left (input.hidden-input)
     -0:14.3.0 core:move-down (input.hidden-input)
     -0:12.2.0 core:move-up (input.hidden-input)
     -0:11.1.0 core:move-right (input.hidden-input)
     -0:10.9.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:09.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:09.4.0 core:move-left (input.hidden-input)
     -0:09.1.0 core:backspace (input.hidden-input)
     -0:08.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:08.3.0 core:move-down (input.hidden-input)
  2x -0:07.6.0 core:move-left (input.hidden-input)
     -0:07.4.0 intentions:highlight (input.hidden-input)
     -0:07.2.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:06.9.0 core:backspace (input.hidden-input)
     -0:06.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -0:05.9.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
autohide-tree-view 0.25.1 
busy-signal 1.4.3 
duplicate-removal 0.1.3 
editorconfig 2.2.2 
file-icons 2.1.15 
git-status 0.3.4 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-caddyfile 0.1.7 
language-docker 1.1.8 
language-dotenv 1.1.1 
language-javascript-jsx 0.3.7 
language-mako 0.6.0 
language-nginx 0.8.0 
language-pug 0.0.21 
language-vue 0.23.1 
linter 2.2.0 
linter-pycodestyle 2.1.3 
linter-stylelint 4.2.0 
linter-swagger 0.4.2 
linter-ui-default 1.6.10 
linter-xo 0.23.1 
multi-cursor 2.1.5 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sort-lines 0.18.0 
todo-show 2.1.0 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.4.0 
vue-hyperclick 0.2.0 
wakatime 7.0.4 
```

**Comment by b4dnewz** [comment]
to me happen only when multiple lines are selected for example 

* select something (highlight)
* press **ctrl+d** many times to find other matches and do multi-line edit
* start typing

when you start typing throws the error, my guess (in my case) it is trying to open a suggestion menu for every single line where the selection is.

**Comment by yvele** [comment]
Same problem with Atom 1.30.0 on MacOSX

**Comment by sompylasar** [comment]
It happens after the TernJS server gets overwhelmed by the number of requests and crashes. The multi-edit [mentioned in this comment](https://github.com/tststs/atom-ternjs/issues/309#issuecomment-386790645) aggravates this issue because there's many requests sent at the same time.

**Comment by tststs** [comment]
A little late to the party :D

For each active cursor the type was queried. Depending on how much cursors where active and how fast the user moved the cursors the server crashed because of endless requests. 0b3ce71 only queries the type for the last cursor. This **should** fix the issue.

**Comment by derMart** [comment]
this issue is still present, so maybe open this issue again?

[Enter steps to reproduce:]

1. just use atom, probably occuring when copy and paste

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: MARTIN-PC
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.3


### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At C:\Users\Martin\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'then' of undefined
    at Client.files (/packages/atom-ternjs/lib/atom-ternjs-client.js:263:7)
    at Client.update (/packages/atom-ternjs/lib/atom-ternjs-client.js:128:17)
    at Type.queryType (/packages/atom-ternjs/lib/atom-ternjs-type.js:205:20)
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:248:31
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1214427)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:547187)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:532330)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1214427)
    at DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2917032)
    at ~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2912534
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1214427)
    at Marker.emitChangeEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:73620)
    at Marker.update (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:72674)
    at Marker.setHeadPosition (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:68833)
    at DisplayMarker.setHeadBufferPosition (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2914387)
    at DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:2914619)
    at changePosition (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:522352)
    at Cursor.changePosition (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:530896)
    at Cursor.setScreenPosition (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:522318)
    at Cursor.moveDown (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:524799)
    at moveCursors.t (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:30888)
    at Array.forEach (<anonymous>)
    at transact (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:33144)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:492268)
    at TextEditor.transact (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:33112)
    at TextEditor.moveDown (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:30871)
    at TextEditor.core:move-down (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:302933)
    at HTMLElement.n.(anonymous function) (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:306938)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1253613)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1249747)
```

### Commands

```
     -2:06.5.0 core:backspace (input.hidden-input)
     -2:06.1.0 core:move-down (input.hidden-input)
  4x -2:01.0 core:backspace (input.hidden-input)
     -1:52.4.0 editor:newline (input.hidden-input)
     -1:52.2.0 intentions:highlight (input.hidden-input)
     -1:52.1.0 core:save (input.hidden-input)
 13x -1:26.2.0 core:backspace (input.hidden-input)
     -1:20.1.0 intentions:highlight (input.hidden-input)
  2x -1:19.7.0 editor:newline (input.hidden-input)
  2x -1:19.5.0 intentions:highlight (input.hidden-input)
     -1:19.2.0 core:save (input.hidden-input)
  3x -1:19 core:move-up (input.hidden-input)
     -1:18.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:18.4.0 editor:newline (input.hidden-input)
  5x -1:12.7.0 core:backspace (input.hidden-input)
     -1:09.9.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
intentions 1.1.2 
language-vue 0.25.0 
language-vue-component 0.5.0 
linter 2.1.4 
linter-ui-default 1.6.1 
linter-xo 0.23.0 
```
