### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by kingteam2017** [tststs/atom-ternjs#314]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.2

### Stack Trace

Uncaught Error: Cannot find module 'underscore-plus'

```
At module.js:457

Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/atom-ternjs-master/lib/atom-ternjs-server.js:51:23)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/atom-ternjs-master/lib/atom-ternjs-manager.js:13:25)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/atom-ternjs-master/lib/atom-ternjs-provider.js:11:26)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/atom-ternjs-master/lib/atom-ternjs.js:15:27)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
  at PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:785:34)
  at PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:430:16)
  at PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:422:12)
  at /app.asar/node_modules/settings-view/lib/package-card.js:84:10)
  at PackageDetailView.completeInitialization (/app.asar/node_modules/settings-view/lib/package-detail-view.js:182:28)
  at PackageDetailView.loadPackage (/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:14)
  at /app.asar/node_modules/settings-view/lib/package-detail-view.js:76:10)
  at callback (/app.asar/node_modules/settings-view/lib/settings-view.js:344:20)
  at SettingsView.getOrCreatePanel (/app.asar/node_modules/settings-view/lib/settings-view.js:349:19)
  at SettingsView.showPanel (/app.asar/node_modules/settings-view/lib/settings-view.js:407:24)
  at SettingsView.showDeferredPanel (/app.asar/node_modules/settings-view/lib/settings-view.js:394:14)
  at SettingsView.initializePanels (/app.asar/node_modules/settings-view/lib/settings-view.js:228:12)
  at /app.asar/node_modules/settings-view/lib/settings-view.js:106:20
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

```

### Commands

```
```

### Non-Core Packages

```
simplified-chinese-menu 5.3.1 
atom-ternjs 0.18.2 
```

**Comment by tststs** [comment]
please reinstall atom. `autocomplete-plus` is a core package and should be available.
