### ISSUE TITLE
Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by jduhls** [tststs/atom-ternjs#329]
[Enter steps to reproduce:]

1. uninstall atom-ternjs
2. install atom-ternjs

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.3

### Stack Trace

Failed to activate the atom-ternjs package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:110:29)
    at Object.requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:31:15)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:107:16)
    at Object.consumeProvider_2_0 (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:86:23)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:658:56
    at Set.forEach (native)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:656:47)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:58.3.0 core:copy (input.hidden-input)
  4x -2:47.8.0 core:backspace (input.hidden-input)
  2x -2:44 core:move-right (input.hidden-input)
  2x -2:43.5.0 editor:newline (input.hidden-input)
     -2:43.3.0 core:paste (input.hidden-input)
 10x -2:42.7.0 core:move-up (input.hidden-input)
     -2:41.6.0 core:move-down (input.hidden-input)
     -2:41.4.0 core:move-right (input.hidden-input)
     -2:41.1.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -2:37.1.0 editor:newline (input.hidden-input)
  5x -2:33.4.0 core:backspace (input.hidden-input)
     -2:29.2.0 editor:newline (input.hidden-input)
     -2:26.6.0 autocomplete-plus:confirm (input.hidden-input)
     -2:24.9.0 core:save (input.hidden-input)
     -2:23.5.0 editor:consolidate-selections (input.hidden-input)
     -2:23.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ternjs 0.18.3 
atom-typescript 11.0.8 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
autocomplete-js-import 1.4.0 
autocomplete-paths 2.11.0 
autocomplete-php 0.3.7 
autocomplete-python 1.10.2 
busy-signal 1.4.3 
color-picker 2.2.5 
compare-files undefined 
file-icons 2.1.11 
file-watcher 1.2.6 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.11.0 
language-apache 1.7.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-php 1.4.0 
linter-tslint 1.7.0 
linter-ui-default 1.6.8 
minimap 4.29.6 
prettier-atom 0.38.0 
project-manager 3.3.5 
react 0.16.2 
toggle-quotes 1.0.1 
```

**Comment by tststs** [comment]
Does this issues still occurs? I haven't been able to reproduce the issue.

**Comment by jduhls** [comment]
I don’t know. Quite a Long time since I’ve used this.
