### ISSUE TITLE
Uncaught TypeError: Cannot read property '_ternDocs' of undefined

### ISSUE THREAD

**Issue by despairblue** [tststs/atom-ternjs#34]
[Enter steps to reproduce below:]

dunno how to reproduce yet.

happened while saving a new file with the contents of: 
```javascript
'use strict';

console.log('hallo');
```

**Atom Version**: 0.182.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.4.20

### Stack Trace

Uncaught TypeError: Cannot read property '_ternDocs' of undefined

```
At /home/despairblue/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:118

TypeError: Cannot read property '_ternDocs' of undefined
  at Provider.module.exports.Provider.setDocumentationContent (/home/despairblue/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:118:30)
  at /home/despairblue/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:175:14
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.selectPrevious (/home/despairblue/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:62:14)
  at atom-text-editor.<anonymous> (/home/despairblue/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -0:19.1 core:move-up (atom-text-editor.editor.is-focused)
     -0:18.9 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:18.9 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.5 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:17.1 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:14.7 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:13.9 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:13.9 snippets:expand (atom-text-editor.editor.is-focused)
     -0:12.2 core:save (atom-text-editor.editor.is-focused)
  2x -0:06.5 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:06.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:03.3 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.1 autocomplete-plus:select-previous (atom-text-editor.editor.is-focused)
     -0:00.8 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:00.6 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.1 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "spell-check"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true
  },
  "atom-ternjs": {
    "coffeeScript": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.3
atom-color-highlight, v3.0.8
atom-jasmine, v0.5.0
atom-ternjs, v0.4.20
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
autocomplete-snippets, v1.0.1
block-travel, v1.0.2
bug-report, v0.6.1
color-picker, v1.4.4
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v0.3.0
file-icons, v1.4.11
filetype-color, v0.1.4
git-log, v0.3.0
git-plus, v4.4.8
go-plus, v3.2.2
grammar-token-limit, v0.1.1
highlight-selected, v0.9.0
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.7
language-dockerfile, v0.1.0
language-haskell, v1.0.0
language-latex, v0.4.1
language-nimrod, v0.1.0
language-puppet, v0.10.0
language-tss, v0.0.1
latex, v0.18.1
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-eslint, v0.3.2
linter-jshint, v0.1.0
linter-puppet-lint, v0.2.8
minimap, v4.3.1
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v4.0.0
minimap-git-diff, v4.0.0
minimap-highlight-selected, v4.1.0
move-panes, v0.1.2
open-last-project, v0.3.1
package-cop, v0.2.2
pane-layout-plus, v0.6.5
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.8.1
test-status, v0.27.1
zentabs, v0.8.2

# Dev
atom-ternjs, v0.4.17
autocomplete-plus, v2.0.2
```

**Comment by tststs** [comment]
this should do the trick. :)
feel free to reopen the issue if the problem still occurs after the next release.

greetings
tststs
