### ISSUE TITLE
Failed to activate the atom-ternjs package

### ISSUE THREAD

**Issue by welblaud** [tststs/atom-ternjs#342]
[Enter steps to reproduce:]

1. Start Atom or Restart the server

**Atom**: 1.25.0-beta2 ia32
**Electron**: 1.7.11
**OS**: Win 7
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.3

### Stack Trace

Failed to activate the atom-ternjs package

```
At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Object.fs.readFileSync (fs.js:517:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Server.readJSON (/packages/atom-ternjs/lib/atom-ternjs-server.js:241:19)
    at Server.readProjectFile (/packages/atom-ternjs/lib/atom-ternjs-server.js:287:21)
    at Server.init (/packages/atom-ternjs/lib/atom-ternjs-server.js:59:24)
    at /packages/atom-ternjs/lib/atom-ternjs-server.js:49:10)
    at Manager.startServer (/packages/atom-ternjs/lib/atom-ternjs-manager.js:106:23)
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:220:43
    at Workspace.observeTextEditors (D:/C_temp/Atom/Atom/resources/app/src/workspace.js:637:59)
    at Manager.registerListeners (/packages/atom-ternjs/lib/atom-ternjs-manager.js:211:42)
    at Manager.activate (/packages/atom-ternjs/lib/atom-ternjs-manager.js:51:10)
    at AtomTernjs.activate (/packages/atom-ternjs/lib/atom-ternjs.js:17:13)
    at Package.activateNow (D:/C_temp/Atom/Atom/resources/app/src/package.js:230:33)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (D:/C_temp/Atom/Atom/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (D:/C_temp/Atom/Atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:/C_temp/Atom/Atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (D:/C_temp/Atom/Atom/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (D:/C_temp/Atom/Atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (D:/C_temp/Atom/Atom/resources/app/src/atom-environment.js:1343:25)
    at EventEmitter.outerCallback (D:/C_temp/Atom/Atom/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -6:11.6.0 intentions:highlight (input.hidden-input)
     -6:03.3.0 autocomplete-plus:cancel (input.hidden-input)
     -5:51.9.0 editor:select-to-beginning-of-word (input.hidden-input)
  4x -5:51 core:select-left (input.hidden-input)
     -5:50.1.0 core:delete (input.hidden-input)
     -5:27.6.0 intentions:highlight (input.hidden-input)
     -5:22.2.0 core:backspace (input.hidden-input)
     -0:25.6.0 atom-ternjs:openConfig (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.3 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
caprice-dark-syntax 2.0.0 
deep-purple-syntax 0.2.18 
duotone-dark-sky-syntax 2.1.0 
existdb 0.8.0 
fonts 3.0.3 
gruvbox 1.0.7 
gruvbox-dark-ui 1.1.0 
gruvbox-plus-syntax 1.3.1 
hyperclick 0.0.0 
ide-java 0.8.1 
ide-typescript 0.7.5 
idle-theme 0.1.0 
intentions 1.1.5 
joehannes-steampunk-ui 0.2.11 
linter 2.2.0 
linter-ui-default 1.7.1 
monokai 0.24.0 
script 3.17.3 
steam-pirate-ui 0.6.1 
```

**Comment by tststs** [comment]
can you post your .tern-project and if possible an example repo where the issue occurs?
thx
