### ISSUE TITLE
Can`t install

### ISSUE THREAD

**Issue by Khuzha** [tststs/atom-ternjs#349]
There was three errors: 

> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.4.0
> gyp info using node@8.9.3 | linux | x64
> gyp http GET https://atom.io/download/electron/v2.0.9/iojs-v2.0.9.tar.gz
> gyp WARN install got an error, rolling back install
> gyp ERR! install error 
> gyp ERR! stack Error: getaddrinfo EAI_AGAIN gh-contractor-zcbenz.s3.amazonaws.com:443
> gyp ERR! stack     at Object._errnoException (util.js:1024:11)
> gyp ERR! stack     at errnoException (dns.js:55:15)
> gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
> gyp ERR! System Linux 4.18.0-10-generic
> gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
> gyp ERR! cwd /home/khuzha/.atom
> gyp ERR! node -v v8.9.3
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 

Second:

> npm ERR! code EAI_AGAIN
> npm ERR! errno EAI_AGAIN
> npm ERR! request to https://www.atom.io/api/packages/atom-ternjs/versions/0.18.3/tarball failed, reason: getaddrinfo EAI_AGAIN www.atom.io:443
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/khuzha/.atom/.apm/_logs/2018-10-31T20_07_10_772Z-debug.log

Third:

**Comment by tststs** [comment]
Have a look into this issue: https://github.com/atom/atom/issues/5148
