### ISSUE TITLE
atom-ternjs: glob support issue

### ISSUE THREAD

**Issue by Sendao** [tststs/atom-ternjs#350]
This error has been seen on Grunt before. It means the Glob version is outdated.
https://github.com/gruntjs/grunt/issues/1401

Steps to reproduce:
1. Use a Samba filesystem with Atom and tern-js

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package 0.18.3

### Stack Trace

Failed to activate the atom-ternjs package

```
At ENOTSUP: operation not supported on socket, scandir 'Z:\var\rad\lib\app.js'

Error: ENOTSUP: operation not supported on socket, scandir 'Z:\var\rad\lib\app.js'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
    at Glob._readdir (/packages/atom-ternjs/node_modules/glob/glob.js:662:20)
    at Glob._process (/packages/atom-ternjs/node_modules/glob/glob.js:446:15)
    at /packages/atom-ternjs/node_modules/glob/glob.js:480:14)
    at Array.forEach (<anonymous>)
    at /packages/atom-ternjs/node_modules/glob/glob.js:479:9)
    at Glob._afterReaddir (/packages/atom-ternjs/node_modules/glob/glob.js:688:15)
    at Glob._readdir (/packages/atom-ternjs/node_modules/glob/glob.js:666:17)
    at Glob._process (/packages/atom-ternjs/node_modules/glob/glob.js:446:15)
    at Glob.iterator (/packages/atom-ternjs/node_modules/glob/glob.js:181:10)
    at Array.forEach (<anonymous>)
    at /packages/atom-ternjs/node_modules/glob/glob.js:179:22)
    at glob (/packages/atom-ternjs/node_modules/glob/glob.js:57:11)
    at /packages/atom-ternjs/node_modules/glob/glob.js:76:10)
    at /packages/atom-ternjs/lib/atom-ternjs-server.js:82:14
    at Array.forEach (<anonymous>)
    at Server.init (/packages/atom-ternjs/lib/atom-ternjs-server.js:80:31)
    at /packages/atom-ternjs/lib/atom-ternjs-server.js:49:10)
    at Manager.startServer (/packages/atom-ternjs/lib/atom-ternjs-manager.js:106:23)
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:220:43
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:425358)
    at Manager.registerListeners (/packages/atom-ternjs/lib/atom-ternjs-manager.js:211:42)
    at Manager.activate (/packages/atom-ternjs/lib/atom-ternjs-manager.js:51:10)
    at AtomTernjs.activate (/packages/atom-ternjs/lib/atom-ternjs.js:17:13)
    at Package.activateNow (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3033048)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1186984)
    at Emitter.emit (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1188425)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:380240)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:380202)
    at n.forEach.e (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:375184)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:375168)
    at emitter.on (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:332690)
```

### Commands

```
     -5:21.5.0 editor:select-to-end-of-word (input.hidden-input)
     -5:18.1.0 editor:newline (input.hidden-input)
     -5:09.7.0 core:move-up (input.hidden-input)
     -5:09.3.0 editor:newline (input.hidden-input)
  4x -5:02.2.0 core:move-down (input.hidden-input)
     -4:49.6.0 core:save (input.hidden-input)
     -4:12 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -4:09.4.0 editor:select-to-first-character-of-line (input.hidden-input)
     -4:09.1.0 core:backspace (input.hidden-input)
     -4:08.8.0 editor:consolidate-selections (input.hidden-input)
     -4:08.8.0 core:cancel (input.hidden-input)
     -4:07.9.0 command-palette:toggle (input.hidden-input)
     -4:05.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -4:04.9.0 core:backspace (input.hidden-input)
     -4:04.5.0 editor:consolidate-selections (input.hidden-input)
     -4:04.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ctags 5.1.2 
atom-ide-ui 0.13.0 
atom-ternjs 0.18.3 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.26 
ide-cpp 0.0.3 
ide-css 0.3.0 
ide-html 0.4.2 
ide-typescript 0.7.9 
minimap 4.29.9 
pretty-json 2.0.3 
script 3.18.1 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
```

**Comment by tststs** [comment]
a2a8998f031184c498067396ce30e04c972cdae9 should fix this issue.
