### ISSUE TITLE
install atom-ternjs 0.19.1 failed (failure only at 64 bit Version)

### ISSUE THREAD

**Issue by JavaAlberto** [tststs/atom-ternjs#365]

**Comment by JavaAlberto** [comment]
I tried to install atom-ternjs on both ways "automatic" via Atom and manual.
In both ways there is the same error during install on a 64 Bit-Windows 10 System
(on my 32 Bit System this error does not exist):
Log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\AlbPe\\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\AlbPe\\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\AlbPe\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\AlbPe\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/atom-ternjs/versions/0.19.1/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=3.1.10',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 137d806561d49ac3
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/atom-ternjs/versions/0.19.1/tarball 2405ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/atom-ternjs/versions/0.19.1/tarball fetched in 2437ms
9 timing stage:loadCurrentTree Completed in 2665ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 4ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule atom-ternjs@0.19.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/resolve-from 376ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/atom-package-deps 384ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/glob 388ms (from cache)
20 silly pacote range manifest for resolve-from@^2.0.0 fetched in 384ms
21 silly resolveWithNewModule resolve-from@2.0.0 checking installable status
22 silly pacote range manifest for atom-package-deps@^5.0.0 fetched in 396ms
23 silly resolveWithNewModule atom-package-deps@5.1.0 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/event-kit 392ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/underscore-plus 388ms (from cache)
26 silly pacote range manifest for glob@^7.1.3 fetched in 396ms
27 silly resolveWithNewModule glob@7.1.4 checking installable status
28 silly pacote range manifest for event-kit@^2.2.0 fetched in 400ms
29 silly resolveWithNewModule event-kit@2.5.3 checking installable status
30 http fetch GET 304 https://registry.npmjs.org/minimatch 400ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/uuid 392ms (from cache)
32 http fetch GET 304 https://registry.npmjs.org/loophole 400ms (from cache)
33 silly pacote range manifest for underscore-plus@^1.6.6 fetched in 396ms
34 silly resolveWithNewModule underscore-plus@1.7.0 checking installable status
35 silly pacote range manifest for minimatch@^3.0.4 fetched in 404ms
36 silly resolveWithNewModule minimatch@3.0.4 checking installable status
37 silly pacote range manifest for uuid@^3.3.2 fetched in 396ms
38 silly resolveWithNewModule uuid@3.3.2 checking installable status
39 silly pacote range manifest for loophole@^1.1.0 fetched in 404ms
40 silly resolveWithNewModule loophole@1.1.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/tern 404ms (from cache)
42 silly pacote range manifest for tern@^0.23.0 fetched in 404ms
43 silly resolveWithNewModule tern@0.23.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/sb-fs 82ms (from cache)
45 silly pacote range manifest for sb-fs@^4.0.0 fetched in 82ms
46 silly resolveWithNewModule sb-fs@4.0.0 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/semver 90ms (from cache)
48 silly pacote range manifest for semver@^6.0.0 fetched in 94ms
49 silly resolveWithNewModule semver@6.3.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/strip-bom-buf 92ms (from cache)
51 silly pacote range manifest for strip-bom-buf@^1.0.0 fetched in 92ms
52 silly resolveWithNewModule strip-bom-buf@1.0.0 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/is-utf8 160ms (from cache)
54 silly pacote range manifest for is-utf8@^0.2.1 fetched in 160ms
55 silly resolveWithNewModule is-utf8@0.2.1 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/inherits 116ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/once 120ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/inflight 120ms (from cache)
59 http fetch GET 304 https://registry.npmjs.org/fs.realpath 120ms (from cache)
60 silly pacote range manifest for inherits@2 fetched in 120ms
61 silly resolveWithNewModule inherits@2.0.4 checking installable status
62 silly pacote range manifest for once@^1.3.0 fetched in 120ms
63 silly resolveWithNewModule once@1.4.0 checking installable status
64 silly pacote range manifest for inflight@^1.0.4 fetched in 120ms
65 silly resolveWithNewModule inflight@1.0.6 checking installable status
66 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 124ms
67 silly resolveWithNewModule fs.realpath@1.0.0 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 120ms (from cache)
69 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 120ms
70 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/wrappy 200ms (from cache)
72 silly pacote range manifest for wrappy@1 fetched in 204ms
73 silly resolveWithNewModule wrappy@1.0.2 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/brace-expansion 72ms (from cache)
75 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 76ms
76 silly resolveWithNewModule brace-expansion@1.1.11 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/concat-map 105ms (from cache)
78 http fetch GET 304 https://registry.npmjs.org/balanced-match 109ms (from cache)
79 silly pacote version manifest for concat-map@0.0.1 fetched in 109ms
80 silly resolveWithNewModule concat-map@0.0.1 checking installable status
81 silly pacote range manifest for balanced-match@^1.0.0 fetched in 109ms
82 silly resolveWithNewModule balanced-match@1.0.0 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/enhanced-resolve 88ms (from cache)
84 silly fetchPackageMetaData error for enhanced-resolve@^2.2.2 Unexpected end of JSON input while parsing near '...kETVQhd0+7T8zqJ30Y1Vp'
85 http fetch GET 304 https://registry.npmjs.org/acorn 104ms (from cache)
86 silly pacote range manifest for acorn@^6.0.0 fetched in 104ms
87 silly resolveWithNewModule acorn@6.2.1 checking installable status
88 http fetch GET 304 https://registry.npmjs.org/acorn-walk 526ms (from cache)
89 silly pacote range manifest for acorn-walk@^6.0.0 fetched in 526ms
90 silly resolveWithNewModule acorn-walk@6.2.0 checking installable status
91 http fetch GET 304 https://registry.npmjs.org/acorn-loose 795ms (from cache)
92 silly pacote range manifest for acorn-loose@^6.0.0 fetched in 795ms
93 silly resolveWithNewModule acorn-loose@6.1.0 checking installable status
94 timing stage:rollbackFailedOptional Completed in 0ms
95 timing stage:runTopLevelLifecycles Completed in 4791ms
96 silly saveTree apm-install-dir-11977-8348-1t4hj9z.8krp
96 silly saveTree `-- atom-ternjs@0.19.1
96 silly saveTree   +-- atom-package-deps@5.1.0
96 silly saveTree   | +-- sb-fs@4.0.0
96 silly saveTree   | | `-- strip-bom-buf@1.0.0
96 silly saveTree   | |   `-- is-utf8@0.2.1
96 silly saveTree   | `-- semver@6.3.0
96 silly saveTree   +-- event-kit@2.5.3
96 silly saveTree   +-- glob@7.1.4
96 silly saveTree   | +-- fs.realpath@1.0.0
96 silly saveTree   | +-- inflight@1.0.6
96 silly saveTree   | | +-- once@1.4.0
96 silly saveTree   | | | `-- wrappy@1.0.2
96 silly saveTree   | | `-- wrappy@1.0.2
96 silly saveTree   | +-- inherits@2.0.4
96 silly saveTree   | +-- minimatch@3.0.4
96 silly saveTree   | | `-- brace-expansion@1.1.11
96 silly saveTree   | |   +-- balanced-match@1.0.0
96 silly saveTree   | |   `-- concat-map@0.0.1
96 silly saveTree   | +-- once@1.4.0
96 silly saveTree   | `-- path-is-absolute@1.0.1
96 silly saveTree   +-- loophole@1.1.0
96 silly saveTree   +-- minimatch@3.0.4
96 silly saveTree   +-- resolve-from@2.0.0
96 silly saveTree   +-- tern@0.23.0
96 silly saveTree   | +-- acorn-loose@6.1.0
96 silly saveTree   | | `-- acorn@6.2.1
96 silly saveTree   | +-- acorn-walk@6.2.0
96 silly saveTree   | `-- acorn@6.2.1
96 silly saveTree   +-- underscore-plus@1.7.0
96 silly saveTree   `-- uuid@3.3.2
97 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...kETVQhd0+7T8zqJ30Y1Vp'
97 verbose stack     at JSON.parse (<anonymous>)
97 verbose stack     at parseJson (C:\Users\AlbPe\AppData\Local\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
97 verbose stack     at consumeBody.call.then.buffer (C:\Users\AlbPe\AppData\Local\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
97 verbose stack     at <anonymous>
97 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
98 verbose cwd C:\Users\AlbPe\AppData\Local\Temp\apm-install-dir-11977-8348-1t4hj9z.8krp
99 verbose Windows_NT 10.0.17134
100 verbose argv "C:\\Users\\AlbPe\\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\AlbPe\\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\AlbPe\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\AlbPe\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/atom-ternjs/versions/0.19.1/tarball" "--runtime=electron" "--target=3.1.10" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
101 verbose node v8.9.3
102 verbose npm  v6.2.0
103 error Unexpected end of JSON input while parsing near '...kETVQhd0+7T8zqJ30Y1Vp'
104 verbose exit [ 1, true ]
