### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined, "reloaded"

### ISSUE THREAD

**Issue by ypresto** [tststs/atom-ternjs#43]
This issue reported as same to #1 by atom, but seems to be different issue.

1. Open sass file, then input "ver" and press Tab key to input "vertical-align"
2. Candidates are shown, 1. vertical, 2. vertical-align, ...
3. Press down key to select 2
4. Uncaught TypeError

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/yuya/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:112

TypeError: Cannot read property 'length' of undefined
  at Provider.module.exports.Provider.setDocumentationContent (/Users/yuya/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:112:38)
  at /Users/yuya/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:170:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.selectNext (/Users/yuya/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:56:14)
  at atom-text-editor.<anonymous> (/Users/yuya/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
  7x -0:13.9 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:13.6 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 29x -0:13.2 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:11.4 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 11x -0:11.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:10.3 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:09.8 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:09.5 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 28x -0:09.1 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  8x -0:06.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -0:05.4 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  8x -0:05.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:03.7 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.0 autocomplete-plus:select-next (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.5 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.5 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/yuya/repo/github.com",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "fancy-new-file",
      "autocomplete-plus",
      "minimap",
      "minimap-highlight-selected"
    ]
  },
  "atom-ternjs": {
    "guess": false,
    "urls": false,
    "coffeeScript": true,
    "inlineFnCompletion": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
atom-ternjs, v0.5.2
auto-update-packages, v0.2.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.3.0
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.0.1
coffee-refactor, v0.6.2
color-picker, v1.4.4
css-snippets, v0.5.0
gulp-snippets, v0.6.0
highlight-selected, v0.9.1
javascript-snippets, v1.0.0
js-refactor, v0.3.0
language-haml, v0.15.0
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-haml, v0.1.1
linter-jscs, v1.7.0
linter-jshint, v0.1.0
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
preview-plus, v1.1.19
recent-files, v0.3.0
refactor, v0.4.1
ruby-block-converter, v3.2.0
ruby-define-method, v0.2.0
ruby-slim, v0.2.0
scope-inspector, v0.2.1
vim-mode, v0.34.0
vim-surround, v0.4.2

# Dev
No dev packages
```

**Comment by ypresto** [comment]
I cannot reproduce this after rebooting atom.

**Comment by dxue2012** [comment]
Reproduction:

1. Open typescript file, then trigger autocomplete-plus by typing any prefix (e.g. "va").
Autocomplete candidates are shown, 1. var, 2. private ...
2. Press down key to select any other candidate
Uncaught TypeError

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/dylandxue2012/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:109

TypeError: Cannot read property 'length' of undefined
  at Provider.module.exports.Provider.setDocumentationContent (/Users/dylandxue2012/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:109:38)
  at /Users/dylandxue2012/.atom/packages/atom-ternjs/lib/atom-ternjs-provider.coffee:167:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.selectNext (/Users/dylandxue2012/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:56:14)
  at atom-text-editor.<anonymous> (/Users/dylandxue2012/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
 17x -0:11.9 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
 18x -0:11.1 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:09.6 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:06.3 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
  2x -0:03.7 autocomplete-plus:select-next (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "color-picker",
      "todo-show",
      "atom-ctags",
      "atom-typescript-tools",
      "language-typescript"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.3
atom-typescript, v0.86.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
highlight-selected, v0.9.1
linter, v0.12.0
minimap, v4.4.0
minimap-highlight-selected, v4.2.0
save-session, v0.11.5
symbols-tree-view, v0.6.1
vim-mode, v0.34.0

# Dev
No dev packages
```

**Comment by ypresto** [comment]
:tada:
