### ISSUE TITLE
Error forcing tern auto-complete

### ISSUE THREAD

**Issue by mapaiva** [tststs/atom-ternjs#47]
Hi,

I installed `atom-ternjs` and tryed to force auto complete with `ctrl-alt-space` and had the following error:

**Atom Version**: 0.187.0
**System**: Windows 8.1
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'autocompleteManager' of undefined

```
At C:\Users\Matheus\.atom\packages\atom-ternjs\lib\atom-ternjs-provider.coffee:133

TypeError: Cannot read property 'autocompleteManager' of undefined
  at Provider.module.exports.Provider.forceCompletion (C:\Users\Matheus\.atom\packages\atom-ternjs\lib\atom-ternjs-provider.coffee:133:26)
  at atom-text-editor.disposables.push.atom.commands.add.tern:startCompletion (C:\Users\Matheus\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:134:18)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Matheus\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:246:29)
  at C:\Users\Matheus\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Matheus\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Matheus\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Matheus\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -0:03.8 tern:startCompletion (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autoflow"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.3
linter, v0.12.0
linter-jshint, v0.1.0
monokai, v0.12.0
save-session, v0.11.5

# Dev
No dev packages
```

### My .tern-project file

```json
{
  "libs": [
    "browser",
    "jquery"
  ],
  "loadEagerly": [
    "js/**/*.js"
  ],
  "plugins": {
    "node": {},
    "complete_strings": {},
    "doc_comment": {
     "fullDocs": true
    }
  }
}
```

**Comment by tststs** [comment]
is autocomplete-plus package installed?

**Comment by mapaiva** [comment]
No it's not. 
I installed the `autocomplete-plus` and it works. Thanks a lot @tststs 

Would be nice to explicit the `autocomplete-plus` previous installation in the README installation steps.

**Comment by tststs** [comment]
I will! :)

glad it worked.

thx
tststs
