### ISSUE TITLE
TypeError: Cannot read property 'node' of null at findTypeAt

### ISSUE THREAD

**Issue by yumitsu** [tststs/atom-ternjs#54]
```
TypeError: Cannot read property 'node' of null at findTypeAt (/Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/plugin/node.js:143:31) 
at /Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:765:16 
at Array.forEach (native) at findExprType (/Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:764:28) 
at Object.findTypeAt [as run] (/Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:788:16) 
at run (/Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:212:30) 
at Object.exports.withContext (/Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:732:18) 
at /Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:219:13 
at analyzeAll (/Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:333:15) 
at doRequest (/Users/yumitsu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:203:5)
```

Looks similar to #35.

Steps to reproduce:

1. Create new JavaScript file
2. Type ```;()```

**Comment by tststs** [comment]
This is related to tern itself, the issue is now closed.
marijnh@488dbd51008461fabc310028f901bff04968d365
