### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by SamVerschueren** [tststs/atom-ternjs#60]
This error actually happens quite frequently. It happens when I type or sometimes when I copy-paste something.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.5.23

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Users/sam/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:136

TypeError: Cannot read property 'startsWith' of undefined
  at Object.<anonymous> (/Users/sam/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:136:42)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3251:33)
  at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3206:7)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3258:41)
  at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3206:7)
  at done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8259:14)
  at XMLHttpRequest.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8600:9)

```

### Commands

```
     -0:17.1.0 core:copy (atom-text-editor.editor)
     -0:13.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.23
atom-typescript, v3.0.5
autoclose-html, v0.15.0
autocomplete-plus, v2.12.0
docblockr, v0.6.3
jshint, v1.3.4
language-jade, v0.4.0
linter, v0.12.1
linter-jscs, v1.10.0
remote-sync, v2.4.1
wercker-status, v0.3.0

# Dev
No dev packages
```

**Comment by tststs** [comment]
Hey,

did you restart after upgrading to ```v0.5.23```?
```v0.5.22``` has thrown this error, but with ```v0.5.23``` it should be fixed.

**Comment by SamVerschueren** [comment]
Restarting Atom did the trick. Thanks for the fast reply.

**Comment by tststs** [comment]
you're welcome! :)
