### ISSUE TITLE
Uncaught TypeError: Cannot read property 'autocompleteManager' of null

### ISSUE THREAD

**Issue by dmiro** [tststs/atom-ternjs#67]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Unknown Windows Version
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.5.24

### Stack Trace

Uncaught TypeError: Cannot read property 'autocompleteManager' of null

```
At C:\Users\david.miro\.atom\packages\atom-ternjs\lib\atom-ternjs-provider.coffee:80

TypeError: Cannot read property 'autocompleteManager' of null
  at Provider.module.exports.Provider.forceCompletion (C:\Users\david.miro\.atom\packages\atom-ternjs\lib\atom-ternjs-provider.coffee:80:22)
  at atom-text-editor.disposables.push.atom.commands.add.tern:startCompletion (C:\Users\david.miro\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:212:18)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\david.miro\AppData\Local\atom\app-0.196.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\david.miro\AppData\Local\atom\app-0.196.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\david.miro\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\david.miro\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\david.miro\AppData\Local\atom\app-0.196.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
  2x -0:25.6.0 core:backspace (atom-text-editor.editor)
     -0:06.6.0 tern:startCompletion (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.24

# Dev
No dev packages
```

**Comment by tststs** [comment]
Did you install the package autocomplete-plus?

**Comment by dmiro** [comment]
You're right. I didn't install autocomplete-plus. Thanks.
