### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by atacraft** [tststs/atom-ternjs#75]
Hi!
I'm working with my team on a big angular project, and we're thinking about switching to atom ... thus, i tried to do a minimal setup of atom using atom-ternjs like this ...

#my .tern-project file

{
  "libs": [
    "ecma5",
    "ecma6",
    "jquery"
  ],
  "loadEagerly": [
    "app/\*\*/\*.js",
    "modules/\*\*/\*.js"
  ],
  "plugins": {
    "complete_strings": {},
    "angular": {},
    "requirejs": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}

but it seems we have too much files and atom-ternjs and his dependencies can't handle this according to the call stack i got ...
#call stack

events.js:141 throw er; // Unhandled 'error' event ^ Error: EMFILE: too many open files, scandir 'modules' at Error (native) at Object.fs.readdirSync (fs.js:805:18) at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28) at Glob._readdir (/home/atacraft/.atom/packages/atom-ternjs/node_modules/tern/node_modules/glob/glob.js:662:20) at Glob._process (/home/atacraft/.atom/packages/atom-ternjs/node_modules/tern/node_modules/glob/glob.js:446:15) at Glob.iterator (/home/atacraft/.atom/packages/atom-ternjs/node_modules/tern/node_modules/glob/glob.js:181:10) at Array.forEach (native) at new Glob (/home/atacraft/.atom/packages/atom-ternjs/node_modules/tern/node_modules/glob/glob.js:179:22) at glob (/home/atacraft/.atom/packages/atom-ternjs/node_modules/tern/node_modules/glob/glob.js:57:11) at Function.globSync (/home/atacraft/.atom/packages/atom-ternjs/node_modules/tern/node_modules/glob/glob.js:76:10)

i found some reading here but it didn't allow me to fix it ... thanks for helping

**Comment by tststs** [comment]
Hey!

Did you try to increase the ressource limit for your system?

e.g.:

```ulimit -n 2048```

**Comment by atacraft** [comment]
Hello,
Thank you for replying ...

I just tried increasing the open files number using the command ulimit ... and you're right ...

using 2048 as argument and with "loadEagerly": [ "app/src/\*\*/\*.js"], it works fine

in fact using "find app/src/ -iname "*.js" | wc -l" command, i have 32 js files in this folder ...

but if i want suitable autocompletion i need to include more folders and even the node_modules folder ... for the whole project i have then  15874  using "find . -iname "*.js" | wc -l" ...

I'm working on a virtual machine and it has 4096 Mo as RAM size and it seems i can't go over this value using ulimit command ...

Maybe i'm wrong to think so, but i don't think increasing open files limit could be a suitable long term solution ... 

regards

**Comment by tststs** [comment]
Does the project really depends on 15874 files? :)
Including the whole node_modules folder isn't a good idea.

You may just load the js-files the project really depends on, like we do in bigger projects.

e.g.:
```
{
  "libs": [
    "browser",
    "ecma5",
    "ecma6"
  ],
  "loadEagerly": [
    "app/**/*.js",
    "modules/**/*.js",
    "node_modules/package-name/lib/lib.js,
    "node_modules/package-name2/lib/lib2.js
  ],
  "plugins": {
    "complete_strings": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

**Comment by pesho** [comment]
I have the same issue. Screenshots here:

http://imgur.com/e6ZEWAk
http://imgur.com/bjsFqNP

> Does the project really depends on 15874 files? :)

Can you explain why this should be a problem? Does ternjs really need to open all these files _simultaneously_?

**Comment by atacraft** [comment]
Only js files are included for "loadEagerly" but i can't do a specific inclusion for each module (would take too much time)
