### ISSUE TITLE
undefined is not a function in pane.js:759

### ISSUE THREAD

**Issue by helarqjsc** [tststs/atom-ternjs#81]
I was editing a js file, pressed Ctrl+S and got a error.

**Atom Version**: 0.200.0
**System**: Windows 7
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\pane.js:759

TypeError: undefined is not a function
    at C:\Users\shi\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:303:88
    at Emitter.module.exports.Emitter.emit (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:985:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:967:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor.js:567:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\pane.js:523:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\pane.js:506:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\workspace.js:585:35)
    at atom-workspace.atom.commands.add.core:save (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\workspace-element.js:314:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:238:29)
    at C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\shi\AppData\Local\atom\app-0.200.0\resources\app.asar\src\window-event-handler.js:178:20)
```

### Commands

```
     -6:44.7.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -6:44.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  5x -6:43.4.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -6:42.4.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -6:41.4.0 core:delete (atom-text-editor.editor.is-focused)
     -6:41.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:40.9.0 core:delete (atom-text-editor.editor.is-focused)
     -6:40.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:40.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:38 core:paste (atom-text-editor.editor.is-focused)
  4x -0:35.3.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:33.5.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:33 core:move-left (atom-text-editor.editor.is-focused)
     -0:26.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:25.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "atom-ctags"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.27.4
atom-jasmine, v0.5.0
atom-ternjs, v0.6.1
autocomplete-paths, v1.0.2
color-picker, v1.7.0
isotope-ui, v2.3.0
jshint, v1.3.7
language-gitignore, v0.2.0
webbox-color, v0.5.7

# Dev
No dev packages
```

**Comment by nxiety** [comment]
Had the exact issue on Windows 8.1 AND linux. In both cases, just uninstalling/reinstalling eventually made it work.

Nothing different, no idea why it's working now where as it wasn't before. It's infuriating.
