### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by averrin** [tststs/atom-ternjs#83]
Just press ctrl+alt+d in js or es6 file

```
/home/user/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:239
TypeError: undefined is not a function
  at atom-text-editor.disposables.push.atom.commands.add.tern:definition (/home/user/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:239:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)
```

**Comment by JCCR** [comment]
Steps to reproduce:
1. Have a project added with some js files
2. Open one of your js files in a tab
3. Create a .tern-project file
4. Save & close the .tern-project file
5. Restart server
6. Everything should be fine
7. Close all files and all tabs, yet still have your project in the tree
8. Restart atom
9. Open one of your js files in a tab
10. Press ctrl-alt-d to find a definition
11. It doesn't work and this error pops up
