### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by despairblue** [tststs/atom-ternjs#86]
[Enter steps to reproduce below:]

1. Open a js, coffee, json or cson file outside of the current project folder (actually I just tried the cson files like the config file for `sync packages` or `project manager`)
2. save the file

Happens under linux as well.

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759

TypeError: undefined is not a function
  at /Users/kietsy/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:173:49
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1020:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:578:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  2x -3:37 core:move-down (atom-text-editor.editor.is-focused)
  3x -3:36.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:35.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:35.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -3:35.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:33.6.0 core:paste (atom-text-editor.editor.is-focused)
     -3:29.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:22.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:15.4.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -3:12.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:44.4.0 window:toggle-dev-tools (a.stack-toggle)
     -0:29.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:28.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:28.2.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:21.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop",
      "navigate",
      "atom-zeal",
      "compare-files",
      "regex-railroad-diagram",
      "atom-color-highlight"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true,
    "ignoredNames": [
      "SCENE"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "atom-ternjs": {
    "coffeeScript": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-alignment, v0.12.1
atom-beautify, v0.27.10
atom-fuzzy-grep, v0.2.0
atom-ternjs, v0.6.4
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
bug-report, v0.7.0
color-picker, v2.0.4
docblockr, v0.7.2
editorconfig, v1.0.0
file-icons, v1.5.7
git-log, v0.4.1
go-plus, v3.3.11
grammar-token-limit, v0.1.1
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.0.0
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.12.0
language-tss, v0.4.0
latex, v0.24.1
linter, v0.12.6
linter-coffeelint, v0.3.2
linter-htmlhint, v0.0.16
linter-js-standard, v0.2.5
linter-js-yaml, v1.0.1
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.8
markdown-scroll-sync, v0.4.0
package-sync, v0.2.0
pdf-view, v0.22.0
project-manager, v1.15.10
react, v0.12.0
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by ymatuhin** [comment]
+1

**Comment by shaungrady** [comment]
[Enter steps to reproduce below:]

1. Opened a lone JS file
2. Made a modification, saved it. Error popped.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.4


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:762

TypeError: undefined is not a function
  at /Users/shaun/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:173:49
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:34.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-railscast-theme.theme-atom-dark-ui)
  5x -0:25.9.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
  2x -0:21.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/shaun/Repositories",
    "disabledPackages": [
      "atom-jade",
      "autocomplete-css",
      "autocomplete-paths"
    ],
    "destroyEmptyPanes": false,
    "followSymlinks": false,
    "themes": [
      "atom-dark-ui",
      "railscast-theme"
    ]
  },
  "atom-ternjs": {
    "documentation": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.3.0
aligner-ruby, v1.4.0
angularjs, v0.3.0
atom-beautify, v0.28.7
atom-ternjs, v0.6.4
atom-typescript, v4.6.9
auto-reveal-in-sidebar, v0.5.0
block-travel, v1.0.2
color-picker, v2.0.7
emmet, v2.3.10
file-icons, v1.5.8
git-projects, v1.14.1
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
language-haml, v0.21.0
language-jade, v0.4.0
linter, v1.0.6
linter-jshint, v0.1.7
linter-jsxhint, v0.1.2
linter-scss-lint, v1.0.5
pain-split, v1.4.0
pigments, v0.8.0
project-manager, v1.15.10
railscast-theme, v0.3.0
react, v0.12.0
ruby-slim, v0.2.0

# Dev
No dev packages
```
