### ISSUE TITLE
Failed to activate package named 'atom-ternjs' TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by jacarma** [tststs/atom-ternjs#88]
Replication:
1. Install atom-ternjs
2. Close and re-open atom
3. The following exception appears in console

    /usr/share/atom/resources/app/src/package.js:240 Failed to activate package named 'atom-ternjs' TypeError: Cannot read property 'path' of null
      at Manager.module.exports.Manager.initServers (/home/javier/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:79:48)
      at new Manager (/home/javier/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:34:6)
      at Object.module.exports.activate (/home/javier/.atom/packages/atom-ternjs/lib/atom-ternjs.coffee:86:20)
      at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:235:27)
      at /usr/share/atom/resources/app/src/package.js:221:28
      at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
      at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:14)
      at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:461:21)
      at /usr/share/atom/resources/app/src/package-manager.js:442:29
      at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:350:16)
      at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:436:19)
      at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:419:46)
      at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:604:21)
      at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
      at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
      at Module._compile (module.js:468:26)
      at Object.Module._extensions..js (module.js:486:10)
      at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:318:12)
      at Module.require (module.js:373:17)
      at require (module.js:392:17)
      at window.onload (file:///usr/share/atom/resources/app/static/index.js:49:25)

**Comment by jacarma** [comment]
I was not using the latest version of atom, it worked after upgrading
