### ISSUE TITLE
Uncaught SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by peteruithoven** [tststs/atom-ternjs#93]
1. Adding a `.tern-project` file to project's root folder (no issues yet) 
2. Fill with content: 
```
{
  "libs": [
      "browser",
      "ecma6"
  ],
}
```

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.6.4

### Stack Trace

Uncaught SyntaxError: Unexpected token }

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A438%2C%22initialPaths%22%3A%5B%22%2FApplications%2FAMPPS%2Fwww%2Fbabel%22%5D%7D:6

SyntaxError: Unexpected token }
  at Object.parse (native)
  at Config.module.exports.Config.getContent (/Users/Peter/.atom/packages/atom-ternjs/lib/atom-ternjs-config.coffee:26:20)
  at Config.module.exports.Config.gatherData (/Users/Peter/.atom/packages/atom-ternjs/lib/atom-ternjs-config.coffee:61:20)
  at Manager.module.exports.Manager.setActiveServerAndClient (/Users/Peter/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:110:15)
  at /Users/Peter/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.coffee:180:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:292:19)
  at Pane.module.exports.Pane.activateNextItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:253:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:370:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:442:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -8:52.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:51.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -8:50.8.0 core:select-up (atom-text-editor.editor.is-focused)
     -8:50.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:50.2.0 core:save (atom-text-editor.editor.is-focused)
     -8:49.6.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -8:49.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -8:44.5.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -8:43.9.0 core:save (atom-text-editor.editor.is-focused)
     -8:36.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -8:35.9.0 core:save (atom-text-editor.editor.is-focused)
  8x -6:21.4.0 core:close (atom-pane.pane.active)
  4x -5:57.8.0 core:save (atom-text-editor.editor.is-focused)
     -5:51.8.0 grammar-selector:show (atom-text-editor.editor)
  4x -5:45.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -5:43 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "linter-jshint",
      "whitespace",
      "secure-copy",
      "scp",
      "remote-sync",
      "jshint",
      "auto-detect-indentation",
      "color-picker",
      "git-control",
      "git-history",
      "git-log",
      "highlight-selected",
      "indentation-indicator",
      "keybinding-cheatsheet",
      "language-docker",
      "language-lua",
      "language-openscad",
      "linter-csslint",
      "linter-js-yaml",
      "linter-luacheck",
      "merge-conflicts",
      "motepair",
      "pretty-json",
      "webbox-color",
      "pigments",
      "linter-js-standard",
      "linter-eslint",
      "Tern"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "atom-ternjs": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.6.4
linter, v1.0.6
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by peteruithoven** [comment]
I now see that I get better errors when I restart the Tern server (*Packages* -> *Atom Ternjs* > *Restart server*) or reload Atom (*View* > *Reload*). 

I think it was my mistake, caused by the `,`. 
The following `.tern-project` does seem to work: 
`{
  "libs": ["browser","ecma6"]
}`
